/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package AdminFrontend;

import AdminBackend.StudentMethods;
import AdminBackend.TutorMethods;
import AdminModels.Student;
import AdminModels.Tutor;
import java.awt.CardLayout;
import java.io.IOException;
import java.util.List;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author User
 */
public class AdminFrame extends javax.swing.JFrame {
    
    CardLayout cl;
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(AdminFrame.class.getName());
    private AStudentMenuPanel studentmenupanel;
    private ATutorMenuPanel tutormenupanel;

    /**
     * Creates new form AdminFrame
     */
    public AdminFrame() {
        initComponents();
        studentmenupanel = new AStudentMenuPanel(this);
        tutormenupanel = new ATutorMenuPanel(this);
        
        cl = (CardLayout) ContainerPanel.getLayout();
        ContainerPanel.add(new AdminMenuPanel(this), "admin");
        ContainerPanel.add(studentmenupanel, "student");
        ContainerPanel.add(tutormenupanel, "tutor");
        ContainerPanel.add(new AStudentRegisterPanel(this), "sregister");
        ContainerPanel.add(new ATutorRegisterPanel(this), "tregister");
        ContainerPanel.add(new AdminProfilePanel(this), "aprofile");
        ContainerPanel.add(new PaymentPanel(this), "payment");
        ContainerPanel.add(new AStudentSubjectRequest(this), "srequest");
        cl.show(ContainerPanel, "admin");
        pack();
        setLocationRelativeTo(null);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        ContainerPanel = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new java.awt.GridBagLayout());

        ContainerPanel.setMaximumSize(new java.awt.Dimension(930, 650));
        ContainerPanel.setRequestFocusEnabled(false);
        ContainerPanel.setLayout(new java.awt.CardLayout());
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        getContentPane().add(ContainerPanel, gridBagConstraints);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    // Method to change panels
    public void switchPanel(String name) {
        DefaultTableModel smodel = this.getStudentTableModel();
        DefaultTableModel tmodel = this.getTutorTableModel();
        StudentMethods.PopulateStudentList(smodel);
        TutorMethods.PopulateTutorList(tmodel);
        cl.show(ContainerPanel, name);
    }
    
    public <T> void switchPanelParameters(String name, T model, List<String> un) {
        DefaultTableModel studenttablemodel = this.getStudentTableModel();
        DefaultTableModel tutortablemodel = this.getTutorTableModel();
        StudentMethods.PopulateStudentList(studenttablemodel);
        TutorMethods.PopulateTutorList(tutortablemodel);
        
        JPanel panel = null;
        switch(name) {
            case "sprofile":
                AStudentProfilePanel sprofile = null;
                try {
                    sprofile = new AStudentProfilePanel(this, (Student)model, un);
                } catch (IOException ex) {
                }
                
                ContainerPanel.add(sprofile, "sprofile");
                
                try {
                    panel = new AStudentProfilePanel(this, (Student)model, un);
                } catch (IOException ex) {
                }
                
                break;


            case "sprofileedit":
                AStudentProfileEditPanel sedit = new AStudentProfileEditPanel(this, (Student)model, un);
                ContainerPanel.add(sedit, "sprofileedit");
                panel = new AStudentProfileEditPanel(this, (Student)model, un);
                break;
                
            case "tprofile":
                ATutorProfilePanel tprofile = null;
                try {
                    tprofile = new ATutorProfilePanel(this, (Tutor)model, un);
                } catch (IOException ex) {
                }
                
                ContainerPanel.add(tprofile, "tprofile");
                
                try {
                    panel = new ATutorProfilePanel(this, (Tutor)model, un);
                } catch (IOException ex) {
                }
                
                break;
                
            case "tprofileedit":
                ATutorProfileEditPanel tedit = new ATutorProfileEditPanel(this, (Tutor)model, un);
                ContainerPanel.add(tedit, "sprofileedit");
                panel = new ATutorProfileEditPanel(this, (Tutor)model, un);
                break;
                
            default:
                throw new IllegalArgumentException("Unknown panel: " + name);
                
        }
        ContainerPanel.add(panel, name);
        cl.show(ContainerPanel, name);
        ContainerPanel.revalidate();
        ContainerPanel.repaint();
    }
    
    public DefaultTableModel getStudentTableModel() {
        return (DefaultTableModel) studentmenupanel.getStudentList().getModel();
    }
    
    public DefaultTableModel getTutorTableModel() {
        return (DefaultTableModel) tutormenupanel.getTutorList().getModel();
    }
    
    /**
     * @param args the command line arguments
     */
    
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
                new AdminFrame().setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel ContainerPanel;
    // End of variables declaration//GEN-END:variables
}
