/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package AdminFrontend;

import ATCLogin.Login;
import AdminBackend.AdminMethods;
import AdminBackend.GeneralMethods;
import javax.swing.JOptionPane;

/**
 *
 * @author User
 */
public class AdminMenuPanel extends javax.swing.JPanel {

    private final AdminFrame parent;
    
    /**
     * Creates new form AdminMenuPanel
     */
    public AdminMenuPanel(AdminFrame parent) {
        this.parent = parent;
        initComponents();
        
        String adminid = AdminMethods.AdminSession.getAdminid();
        String adminname = AdminMethods.GetAdminName(adminid);
        String greeting = GeneralMethods.GetGreeting();
        WelcomeLabel.setText(greeting + ", " + adminname);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        AdminPage = new javax.swing.JPanel();
        AdminMenuOptions = new javax.swing.JPanel();
        StudentMenuButton = new javax.swing.JButton();
        TutorMenuButton = new javax.swing.JButton();
        PaymentButton = new javax.swing.JButton();
        ProfileButton = new javax.swing.JButton();
        LogOutButton = new javax.swing.JButton();
        WelcomeLabel = new javax.swing.JLabel();

        AdminPage.setMaximumSize(new java.awt.Dimension(930, 650));
        AdminPage.setMinimumSize(new java.awt.Dimension(930, 650));
        AdminPage.setPreferredSize(new java.awt.Dimension(930, 650));
        AdminPage.setLayout(new java.awt.GridBagLayout());

        AdminMenuOptions.setPreferredSize(new java.awt.Dimension(600, 400));
        AdminMenuOptions.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        StudentMenuButton.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        StudentMenuButton.setText("Student Management");
        StudentMenuButton.setBorderPainted(false);
        StudentMenuButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                StudentMenuButtonActionPerformed(evt);
            }
        });
        AdminMenuOptions.add(StudentMenuButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 70, 290, 120));

        TutorMenuButton.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        TutorMenuButton.setText("Tutor Management");
        TutorMenuButton.setBorderPainted(false);
        TutorMenuButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TutorMenuButtonActionPerformed(evt);
            }
        });
        AdminMenuOptions.add(TutorMenuButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 70, 290, 120));

        PaymentButton.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        PaymentButton.setText("Payment");
        PaymentButton.setBorderPainted(false);
        PaymentButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PaymentButtonActionPerformed(evt);
            }
        });
        AdminMenuOptions.add(PaymentButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 210, 290, 120));

        ProfileButton.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        ProfileButton.setText("Profile");
        ProfileButton.setBorderPainted(false);
        ProfileButton.setPreferredSize(new java.awt.Dimension(82, 32));
        ProfileButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ProfileButtonActionPerformed(evt);
            }
        });
        AdminMenuOptions.add(ProfileButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 210, 290, 120));

        LogOutButton.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        LogOutButton.setText("Log Out");
        LogOutButton.setPreferredSize(new java.awt.Dimension(82, 32));
        LogOutButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LogOutButtonActionPerformed(evt);
            }
        });
        AdminMenuOptions.add(LogOutButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 360, 130, 40));

        WelcomeLabel.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        WelcomeLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        WelcomeLabel.setText("Welcome, admin!");
        WelcomeLabel.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        AdminMenuOptions.add(WelcomeLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 600, -1));

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        AdminPage.add(AdminMenuOptions, gridBagConstraints);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 930, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(AdminPage, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 650, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(AdminPage, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void StudentMenuButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_StudentMenuButtonActionPerformed
        parent.switchPanel("student");
        
    }//GEN-LAST:event_StudentMenuButtonActionPerformed

    private void TutorMenuButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TutorMenuButtonActionPerformed
        parent.switchPanel("tutor");
    }//GEN-LAST:event_TutorMenuButtonActionPerformed

    private void PaymentButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PaymentButtonActionPerformed
        parent.switchPanel("payment");
    }//GEN-LAST:event_PaymentButtonActionPerformed

    private void ProfileButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ProfileButtonActionPerformed
        parent.switchPanel("aprofile");
    }//GEN-LAST:event_ProfileButtonActionPerformed

    private void LogOutButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LogOutButtonActionPerformed
        int result = JOptionPane.showConfirmDialog(this, "Are you sure you want to log out?", "Logout Confirmation", JOptionPane.YES_NO_OPTION);
        if (result == JOptionPane.YES_OPTION) {
            Login login = new Login();
            login.setVisible(true);
            parent.dispose();
        }
    }//GEN-LAST:event_LogOutButtonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel AdminMenuOptions;
    private javax.swing.JPanel AdminPage;
    private javax.swing.JButton LogOutButton;
    private javax.swing.JButton PaymentButton;
    private javax.swing.JButton ProfileButton;
    private javax.swing.JButton StudentMenuButton;
    private javax.swing.JButton TutorMenuButton;
    private javax.swing.JLabel WelcomeLabel;
    // End of variables declaration//GEN-END:variables
}
