/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package AdminFrontend;

import AdminBackend.AdminMethods.AdminSession;
import AdminBackend.GeneralMethods;
import java.io.BufferedReader;
import java.io.FileReader;
import java.io.IOException;
import java.nio.file.Files;
import java.nio.file.Paths;
import java.util.List;
import javax.swing.JButton;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author User
 */
public class AdminProfilePanel extends javax.swing.JPanel {
    
    private final AdminFrame parent;
    String currentadminid = AdminSession.getAdminid();
    String adminusername;
    String adminpassword;

    /**
     * Creates new form AdminProfile
     */
    public AdminProfilePanel(AdminFrame parent) {
        this.parent = parent;
        initComponents();
        
        // Load admin's profile picture
        GeneralMethods.LoadPFP(AdminProfilePFP, "Profile Pictures/"+ currentadminid +".jpg");
        
        // Load admin's work schedule into JTable
        DefaultTableModel adminschedtable = (DefaultTableModel) AdminScheduleTable.getModel();
        adminschedtable.setRowCount(0);
        try {
            FileReader fr = new FileReader("Text Files/adminschedules.txt");
            BufferedReader br = new BufferedReader(fr);

            String line;
            
            while ((line = br.readLine()) != null) {
                String[] parts = line.split(",");
                if (parts[0].equals(currentadminid)) {
                    Object[] row = new Object[] {parts[1], parts[2]};
                    adminschedtable.addRow(row);
                }
            }
        } catch (IOException ex) {
            ex.printStackTrace();
        }
        
        // Get admin login credentials from users.txt
        try {
            FileReader fr = new FileReader("Text Files/users.txt");
            BufferedReader br = new BufferedReader(fr);

            String line;
            
            while ((line = br.readLine()) != null) {
                String[] parts = line.split(",");
                String id = parts[0];
                String username = parts[1];
                String password = parts[2];
                if (parts[0].equals(currentadminid)) {
                    adminusername = parts[1];
                    adminpassword = parts[2];
                }
            }
        } catch (IOException ex) {
            ex.printStackTrace();
        }
        
        // Replace placeholder JLabels with actual admin information
        try {
            FileReader fr = new FileReader("Text Files/admins.txt");
            BufferedReader br = new BufferedReader(fr);

            String line;
            
            while ((line = br.readLine()) != null) {
                String[] parts = line.split(",");
                String adminid = parts[0];
                String adminname = parts[1];
                String adminph = parts[2];
                String adminemail = parts[3];
                
                if (parts[0].equals(currentadminid)) {
                    AdminIDField.setText(adminid);
                    AdminNameField.setText(adminname);
                    AdminUsernameField.setText(adminusername);
                    AdminPHField.setText(adminph);
                    AdminEmailField.setText(adminemail);
                }
            }
        } catch (IOException ex) {
            ex.printStackTrace();
        }
    }

    public void setAdminEmailField(String email) {
        this.AdminEmailField.setText(email);
    }

    public void setAdminPHField(String ph) {
        this.AdminPHField.setText(ph);
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        AdminProfilePage = new javax.swing.JPanel();
        StudentInfoTab = new javax.swing.JPanel();
        jSeparator1 = new javax.swing.JSeparator();
        EditAdminInfoButton = new javax.swing.JButton();
        AdminProfileBackButton = new javax.swing.JButton();
        ResetPFPButton = new javax.swing.JButton();
        ChangePFPButton = new javax.swing.JButton();
        LeftPanel = new javax.swing.JPanel();
        StudentIdNamePanel = new javax.swing.JPanel();
        AdminIDLabel = new javax.swing.JLabel();
        AdminNameLabel = new javax.swing.JLabel();
        AdminUsernameLabel = new javax.swing.JLabel();
        AdminIDField = new javax.swing.JLabel();
        AdminNameField = new javax.swing.JLabel();
        AdminUsernameField = new javax.swing.JLabel();
        AdminProfilePFP = new AdminFrontend.ImagePanel();
        RightPanel = new javax.swing.JPanel();
        StudentInfoLabel = new javax.swing.JPanel();
        ContactInformationLabel = new javax.swing.JLabel();
        AdminPHLabel = new javax.swing.JLabel();
        AdminEmailLabel = new javax.swing.JLabel();
        AdminPHField = new javax.swing.JLabel();
        AdminEmailField = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        AdminScheduleTable = new javax.swing.JTable();
        PPersonalInfoLabel2 = new javax.swing.JLabel();
        ChangeAdminLoginButton = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        StudentManagementTitle = new javax.swing.JLabel();

        AdminProfilePage.setMaximumSize(new java.awt.Dimension(930, 650));
        AdminProfilePage.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        StudentInfoTab.setMaximumSize(new java.awt.Dimension(850, 500));
        StudentInfoTab.setMinimumSize(new java.awt.Dimension(850, 500));
        StudentInfoTab.setPreferredSize(new java.awt.Dimension(850, 500));
        StudentInfoTab.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jSeparator1.setOrientation(javax.swing.SwingConstants.VERTICAL);
        StudentInfoTab.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 20, 10, 460));

        EditAdminInfoButton.setText("Edit Contact Information");
        EditAdminInfoButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EditAdminInfoButtonActionPerformed(evt);
            }
        });
        StudentInfoTab.add(EditAdminInfoButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 445, 180, 35));

        AdminProfileBackButton.setText("Back");
        AdminProfileBackButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AdminProfileBackButtonActionPerformed(evt);
            }
        });
        StudentInfoTab.add(AdminProfileBackButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(830, 445, 70, 35));

        ResetPFPButton.setText("Reset Profile Picture");
        ResetPFPButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ResetPFPButtonActionPerformed(evt);
            }
        });
        StudentInfoTab.add(ResetPFPButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 445, 200, 35));

        ChangePFPButton.setText("Change Profile Picture");
        ChangePFPButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ChangePFPButtonActionPerformed(evt);
            }
        });
        StudentInfoTab.add(ChangePFPButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 394, 200, 35));

        LeftPanel.setMaximumSize(new java.awt.Dimension(300, 500));
        LeftPanel.setMinimumSize(new java.awt.Dimension(300, 500));
        LeftPanel.setPreferredSize(new java.awt.Dimension(300, 500));
        LeftPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        StudentIdNamePanel.setMaximumSize(new java.awt.Dimension(200, 80));
        StudentIdNamePanel.setMinimumSize(new java.awt.Dimension(200, 80));
        StudentIdNamePanel.setPreferredSize(new java.awt.Dimension(200, 80));
        StudentIdNamePanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        AdminIDLabel.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        AdminIDLabel.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        AdminIDLabel.setText("Admin ID:");
        AdminIDLabel.setToolTipText("");
        AdminIDLabel.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);
        StudentIdNamePanel.add(AdminIDLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 80, -1));

        AdminNameLabel.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        AdminNameLabel.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        AdminNameLabel.setText("Name:");
        AdminNameLabel.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);
        StudentIdNamePanel.add(AdminNameLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 30, 80, -1));

        AdminUsernameLabel.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        AdminUsernameLabel.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        AdminUsernameLabel.setText("Username:");
        AdminUsernameLabel.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);
        StudentIdNamePanel.add(AdminUsernameLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 60, 80, -1));

        AdminIDField.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        AdminIDField.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        AdminIDField.setText("Admin ID");
        AdminIDField.setToolTipText("");
        AdminIDField.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);
        StudentIdNamePanel.add(AdminIDField, new org.netbeans.lib.awtextra.AbsoluteConstraints(85, 0, 115, -1));

        AdminNameField.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        AdminNameField.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        AdminNameField.setText("Admin Name");
        AdminNameField.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);
        StudentIdNamePanel.add(AdminNameField, new org.netbeans.lib.awtextra.AbsoluteConstraints(85, 30, 115, -1));

        AdminUsernameField.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        AdminUsernameField.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        AdminUsernameField.setText("Username");
        AdminUsernameField.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);
        StudentIdNamePanel.add(AdminUsernameField, new org.netbeans.lib.awtextra.AbsoluteConstraints(85, 60, 115, -1));

        LeftPanel.add(StudentIdNamePanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 230, 200, 140));

        AdminProfilePFP.setMaximumSize(new java.awt.Dimension(200, 200));
        AdminProfilePFP.setMinimumSize(new java.awt.Dimension(200, 200));

        javax.swing.GroupLayout AdminProfilePFPLayout = new javax.swing.GroupLayout(AdminProfilePFP);
        AdminProfilePFP.setLayout(AdminProfilePFPLayout);
        AdminProfilePFPLayout.setHorizontalGroup(
            AdminProfilePFPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 200, Short.MAX_VALUE)
        );
        AdminProfilePFPLayout.setVerticalGroup(
            AdminProfilePFPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 200, Short.MAX_VALUE)
        );

        LeftPanel.add(AdminProfilePFP, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 200, 200));

        StudentInfoTab.add(LeftPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 20, 200, 370));

        RightPanel.setMaximumSize(new java.awt.Dimension(630, 500));
        RightPanel.setMinimumSize(new java.awt.Dimension(630, 500));

        StudentInfoLabel.setMaximumSize(new java.awt.Dimension(10, 10));
        StudentInfoLabel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        ContactInformationLabel.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        ContactInformationLabel.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        ContactInformationLabel.setText("Contact Information");
        ContactInformationLabel.setToolTipText("");
        ContactInformationLabel.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);
        StudentInfoLabel.add(ContactInformationLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        AdminPHLabel.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        AdminPHLabel.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        AdminPHLabel.setText("Phone Number:");
        AdminPHLabel.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);
        StudentInfoLabel.add(AdminPHLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 40, -1, -1));

        AdminEmailLabel.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        AdminEmailLabel.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        AdminEmailLabel.setText("Email Address:");
        AdminEmailLabel.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);
        StudentInfoLabel.add(AdminEmailLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 70, -1, -1));

        AdminPHField.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        AdminPHField.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        AdminPHField.setText("-");
        AdminPHField.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);
        StudentInfoLabel.add(AdminPHField, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 40, -1, -1));

        AdminEmailField.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        AdminEmailField.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        AdminEmailField.setText("-");
        AdminEmailField.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);
        StudentInfoLabel.add(AdminEmailField, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 70, -1, -1));

        AdminScheduleTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null},
                {null, null},
                {null, null},
                {null, null}
            },
            new String [] {
                "Day", "Working Hours"
            }
        ));
        AdminScheduleTable.setMaximumSize(new java.awt.Dimension(150, 150));
        AdminScheduleTable.setMinimumSize(new java.awt.Dimension(150, 150));
        AdminScheduleTable.setPreferredSize(new java.awt.Dimension(150, 150));
        AdminScheduleTable.setRowHeight(30);
        AdminScheduleTable.setRowMargin(5);
        AdminScheduleTable.setRowSelectionAllowed(false);
        jScrollPane1.setViewportView(AdminScheduleTable);

        StudentInfoLabel.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 180, 600, 180));

        PPersonalInfoLabel2.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        PPersonalInfoLabel2.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        PPersonalInfoLabel2.setText("Work Schedule");
        PPersonalInfoLabel2.setToolTipText("");
        PPersonalInfoLabel2.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);
        StudentInfoLabel.add(PPersonalInfoLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 140, 290, -1));

        javax.swing.GroupLayout RightPanelLayout = new javax.swing.GroupLayout(RightPanel);
        RightPanel.setLayout(RightPanelLayout);
        RightPanelLayout.setHorizontalGroup(
            RightPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, RightPanelLayout.createSequentialGroup()
                .addContainerGap(26, Short.MAX_VALUE)
                .addComponent(StudentInfoLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 608, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        RightPanelLayout.setVerticalGroup(
            RightPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(RightPanelLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(StudentInfoLabel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(120, Short.MAX_VALUE))
        );

        StudentInfoTab.add(RightPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(257, 0, 640, 420));

        ChangeAdminLoginButton.setText("Change Admin Login Credentials");
        ChangeAdminLoginButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ChangeAdminLoginButtonActionPerformed(evt);
            }
        });
        StudentInfoTab.add(ChangeAdminLoginButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 445, 230, 35));

        AdminProfilePage.add(StudentInfoTab, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 120, 930, 530));

        jPanel2.setBackground(new java.awt.Color(184, 186, 191));
        jPanel2.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        StudentManagementTitle.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        StudentManagementTitle.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        StudentManagementTitle.setText("Admin Profile");
        StudentManagementTitle.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(StudentManagementTitle, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 926, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addComponent(StudentManagementTitle)
                .addContainerGap(33, Short.MAX_VALUE))
        );

        AdminProfilePage.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 930, 100));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 930, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(AdminProfilePage, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 650, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(AdminProfilePage, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void EditAdminInfoButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EditAdminInfoButtonActionPerformed
        String adminph = null;
        String adminemail = null;
        
        try {
            FileReader fr = new FileReader("Text Files/admins.txt");
            BufferedReader br = new BufferedReader(fr);

            String line;
            
            while ((line = br.readLine()) != null) {
                String[] parts = line.split(",");

                if (parts[0].equals(currentadminid)) {
                    adminph = parts[2];
                    adminemail = parts[3];
                }
            }
        } catch (IOException ex) {
            ex.printStackTrace();
        }
        
        PopupContactInfo popup = new PopupContactInfo(adminph, adminemail);
        JButton[] options = {popup.getCIOKButton(), popup.getCICancelButton()};
        JButton okbutton = options[0];
        
        while (true) {
            int choice = JOptionPane.showOptionDialog(this, popup, "Change Contact Information", JOptionPane.DEFAULT_OPTION, JOptionPane.PLAIN_MESSAGE, null, options, okbutton);
            if (popup.getCIChoice() == 0) {
                String newph = "+60" + popup.getNewPH().trim();
                String newemail = popup.getNewEmail().trim();

                boolean exists = false;

                try (BufferedReader br = new BufferedReader(new FileReader("Text Files/admins.txt"))) {
                    String line;

                    while ((line = br.readLine()) != null) {
                        String[] parts = line.split(",");

                        if (parts[0].equals(currentadminid)) {
                            continue;
                        } else if (parts[2].equalsIgnoreCase(newph.trim()) || parts[3].equalsIgnoreCase(newemail.trim())) {
                            JOptionPane.showMessageDialog(null, "Error: Phone number or email already exists.");
                            popup.setEmail(adminemail);
                            popup.setPH(adminph);
                            exists = true;
                            break;
                        }
                    }
                } catch (IOException ex) {
                    ex.printStackTrace();
                }

                if (exists) continue;

                try {
                    List<String> lines = Files.readAllLines(Paths.get("Text Files/admins.txt"));
                    for (int i = 0; i < lines.size(); i++) {
                        String[] parts = lines.get(i).split(",");
                        if (parts[0].equals(currentadminid)) {
                            parts[2] = newph;
                            parts[3] = newemail;
                            lines.set(i, String.join(",", parts));
                            break;
                        }
                    }
                    Files.write(Paths.get("Text Files/admins.txt"), lines);
                } catch (IOException ex) {
                    ex.printStackTrace();
                }

                JOptionPane.showMessageDialog(this, "Contact information successfully updated!");
                AdminPHField.setText(newph);
                AdminEmailField.setText(newemail);
                popup.setPH(newph);
                popup.setEmail(newemail);
                revalidate();
                repaint();
                break;
            } else {
                break;
            }
        }
    }//GEN-LAST:event_EditAdminInfoButtonActionPerformed

    private void AdminProfileBackButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AdminProfileBackButtonActionPerformed
        parent.switchPanel("admin");
    }//GEN-LAST:event_AdminProfileBackButtonActionPerformed

    private void ResetPFPButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ResetPFPButtonActionPerformed
        GeneralMethods.ResetPFP(this, currentadminid);
        GeneralMethods.LoadPFP(AdminProfilePFP, "Profile Pictures/"+ currentadminid +".jpg");
    }//GEN-LAST:event_ResetPFPButtonActionPerformed

    private void ChangePFPButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ChangePFPButtonActionPerformed
        GeneralMethods.ChangePFP(AdminProfilePFP, this, currentadminid);
    }//GEN-LAST:event_ChangePFPButtonActionPerformed

    private void ChangeAdminLoginButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ChangeAdminLoginButtonActionPerformed
        PopupLoginCredentials popup = new PopupLoginCredentials(GeneralMethods.GetLoginCreds(currentadminid));
        JButton[] options = {popup.getLCOKButton(), popup.getLCCancelButton()};
        JButton okbutton = options[0];
        
        while (true) {
            JOptionPane.showOptionDialog(this, popup, "Change Login Credentials", JOptionPane.DEFAULT_OPTION, JOptionPane.PLAIN_MESSAGE, null, options, okbutton);

            if (popup.getLCChoice() == 0) {
                if (GeneralMethods.ValidateUsername(currentadminid, popup.getNewUsername().trim())) {
                    int choice = JOptionPane.showConfirmDialog(this, "Confirm changes to admin login credentials?", "Login Credentials Change Confirmation", JOptionPane.YES_NO_OPTION);
                    if (choice == JOptionPane.OK_OPTION) {
                        String newusername = popup.getNewUsername();
                        String newpassword = popup.getNewPassword();
                        GeneralMethods.SaveNewLogin(currentadminid, newusername, newpassword);
                        AdminUsernameField.setText(newusername);
                        popup.setUsername(newusername);
                        popup.setPassword(newpassword);
                        revalidate();
                        repaint();
                        break;
                    }
                } else {
                    popup.getUsernameField().setText(adminusername);
                }  
            } else {
                break;
            }
        }
        
        

    }//GEN-LAST:event_ChangeAdminLoginButtonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel AdminEmailField;
    private javax.swing.JLabel AdminEmailLabel;
    private javax.swing.JLabel AdminIDField;
    private javax.swing.JLabel AdminIDLabel;
    private javax.swing.JLabel AdminNameField;
    private javax.swing.JLabel AdminNameLabel;
    private javax.swing.JLabel AdminPHField;
    private javax.swing.JLabel AdminPHLabel;
    private javax.swing.JButton AdminProfileBackButton;
    private AdminFrontend.ImagePanel AdminProfilePFP;
    private javax.swing.JPanel AdminProfilePage;
    private javax.swing.JTable AdminScheduleTable;
    private javax.swing.JLabel AdminUsernameField;
    private javax.swing.JLabel AdminUsernameLabel;
    private javax.swing.JButton ChangeAdminLoginButton;
    private javax.swing.JButton ChangePFPButton;
    private javax.swing.JLabel ContactInformationLabel;
    private javax.swing.JButton EditAdminInfoButton;
    private javax.swing.JPanel LeftPanel;
    private javax.swing.JLabel PPersonalInfoLabel2;
    private javax.swing.JButton ResetPFPButton;
    private javax.swing.JPanel RightPanel;
    private javax.swing.JPanel StudentIdNamePanel;
    private javax.swing.JPanel StudentInfoLabel;
    private javax.swing.JPanel StudentInfoTab;
    private javax.swing.JLabel StudentManagementTitle;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    // End of variables declaration//GEN-END:variables
}
