/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package AdminFrontend;

import AdminBackend.GeneralMethods;
import AdminBackend.StudentMethods;
import AdminModels.Student;
import java.io.IOException;
import java.util.List;
import javax.swing.JButton;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author User
 */
public class AStudentProfilePanel extends javax.swing.JPanel {

    private final AdminFrame parent;
    Student saveselectedstudent;
    List<String> saveselectedlogin;
    PopupLoginCredentials changeloginpopup;
    DefaultTableModel subjecttablemodel;
    
    /**
     * Creates new form AStudentProfilePanel
     */
    public AStudentProfilePanel(AdminFrame parent, Student selectedstudent, List<String> selectedlogin) throws IOException {
        this.parent = parent;
        this.saveselectedstudent = selectedstudent;
        this.saveselectedlogin = selectedlogin;
        
        initComponents();
                
        if (selectedstudent != null) {
            CPStudentIDLabel.setText(selectedstudent.getStudentid());
            CPStudentNameLabel.setText(selectedstudent.getStudentname());
            CPStudentUsernameLabel.setText(saveselectedlogin.get(0));
            CPAgeLabel.setText(Integer.toString(selectedstudent.getStudentage()));
            CPGenderLabel.setText(selectedstudent.getStudentgender());
            CPICLabel.setText(selectedstudent.getStudentic());
            CPEmailLabel.setText(selectedstudent.getStudentph());
            CPPHLabel.setText(selectedstudent.getStudentemail());
            CPAddressLabel.setText(selectedstudent.getStudentaddress());
            CPLevelLabel.setText(selectedstudent.getStudentlevel());
            CPEnrolLabel.setText(selectedstudent.getStudentenrol());
            subjecttablemodel = (DefaultTableModel) SubjectTable.getModel();
            StudentMethods.PopulateSubjectList(subjecttablemodel, selectedstudent.getStudentid(), selectedstudent.getStudentsubjects());
            GeneralMethods.LoadPFP(StudentProfilePFP, "Profile Pictures/"+ saveselectedstudent.getStudentid() +".jpg");
            
            StudentMethods.PopulateStudentPaymentHistory((DefaultTableModel) StudentPaymentHistory.getModel(), saveselectedstudent.getStudentid());
        }
        
        changeloginpopup = new PopupLoginCredentials(saveselectedlogin);
    }


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        StudentProfilePage = new javax.swing.JPanel();
        StudentProfileTabbedPane = new javax.swing.JTabbedPane();
        StudentInfoTab = new javax.swing.JPanel();
        jSeparator1 = new javax.swing.JSeparator();
        EditStudentInfoButton = new javax.swing.JButton();
        ChangeStudentLoginButton = new javax.swing.JButton();
        StudentProfileBackButton = new javax.swing.JButton();
        DeleteStudentButton = new javax.swing.JButton();
        ResetPFPButton = new javax.swing.JButton();
        LeftPanel = new javax.swing.JPanel();
        StudentProfilePFP = new AdminFrontend.ImagePanel();
        StudentIdNamePanel = new javax.swing.JPanel();
        PStudentIDLabel = new javax.swing.JLabel();
        PStudentNameLabel = new javax.swing.JLabel();
        PStudentUsernameLabel = new javax.swing.JLabel();
        CPStudentIDLabel = new javax.swing.JLabel();
        CPStudentNameLabel = new javax.swing.JLabel();
        CPStudentUsernameLabel = new javax.swing.JLabel();
        RightPanel = new javax.swing.JPanel();
        StudentInfoLabel = new javax.swing.JPanel();
        PPersonalInfoLabel1 = new javax.swing.JLabel();
        PAgeLabel = new javax.swing.JLabel();
        PGenderLabel = new javax.swing.JLabel();
        PICLabel = new javax.swing.JLabel();
        PPHLabel = new javax.swing.JLabel();
        PEmailLabel = new javax.swing.JLabel();
        PAddressLabel = new javax.swing.JLabel();
        PStudentInfoLabel = new javax.swing.JLabel();
        PLevelLabel = new javax.swing.JLabel();
        PEnrolLabel = new javax.swing.JLabel();
        CPAgeLabel = new javax.swing.JLabel();
        CPGenderLabel = new javax.swing.JLabel();
        CPICLabel = new javax.swing.JLabel();
        CPEmailLabel = new javax.swing.JLabel();
        CPPHLabel = new javax.swing.JLabel();
        CPAddressLabel = new javax.swing.JLabel();
        CPLevelLabel = new javax.swing.JLabel();
        CPEnrolLabel = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        SubjectTable = new javax.swing.JTable();
        PPersonalInfoLabel2 = new javax.swing.JLabel();
        PPersonalInfoLabel3 = new javax.swing.JLabel();
        StudentPaymentTab = new javax.swing.JPanel();
        StudentPaymentHistoryScrollPane = new javax.swing.JScrollPane();
        StudentPaymentHistory = new javax.swing.JTable();
        StudentProfileBackButton1 = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        StudentManagementTitle = new javax.swing.JLabel();

        StudentProfilePage.setMaximumSize(new java.awt.Dimension(930, 650));
        StudentProfilePage.setMinimumSize(new java.awt.Dimension(930, 650));
        StudentProfilePage.setPreferredSize(new java.awt.Dimension(930, 650));
        StudentProfilePage.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        StudentProfileTabbedPane.setMaximumSize(new java.awt.Dimension(850, 500));
        StudentProfileTabbedPane.setMinimumSize(new java.awt.Dimension(850, 500));
        StudentProfileTabbedPane.setPreferredSize(new java.awt.Dimension(850, 500));

        StudentInfoTab.setMaximumSize(new java.awt.Dimension(200, 200));
        StudentInfoTab.setMinimumSize(new java.awt.Dimension(200, 200));
        StudentInfoTab.setPreferredSize(new java.awt.Dimension(200, 200));
        StudentInfoTab.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jSeparator1.setOrientation(javax.swing.SwingConstants.VERTICAL);
        StudentInfoTab.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 20, 10, 460));

        EditStudentInfoButton.setText("Edit Student Information");
        EditStudentInfoButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EditStudentInfoButtonActionPerformed(evt);
            }
        });
        StudentInfoTab.add(EditStudentInfoButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 435, 170, 35));

        ChangeStudentLoginButton.setText("Change Student Login Credentials");
        ChangeStudentLoginButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ChangeStudentLoginButtonActionPerformed(evt);
            }
        });
        StudentInfoTab.add(ChangeStudentLoginButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 435, 230, 35));

        StudentProfileBackButton.setText("Back");
        StudentProfileBackButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                StudentProfileBackButtonActionPerformed(evt);
            }
        });
        StudentInfoTab.add(StudentProfileBackButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(830, 435, 70, 35));

        DeleteStudentButton.setText("Delete");
        DeleteStudentButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DeleteStudentButtonActionPerformed(evt);
            }
        });
        StudentInfoTab.add(DeleteStudentButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 435, 90, 35));

        ResetPFPButton.setText("Reset Profile Picture");
        ResetPFPButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ResetPFPButtonActionPerformed(evt);
            }
        });
        StudentInfoTab.add(ResetPFPButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 435, 200, 35));

        LeftPanel.setMaximumSize(new java.awt.Dimension(300, 500));
        LeftPanel.setMinimumSize(new java.awt.Dimension(300, 500));
        LeftPanel.setPreferredSize(new java.awt.Dimension(300, 500));
        LeftPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        StudentProfilePFP.setMaximumSize(new java.awt.Dimension(200, 200));
        StudentProfilePFP.setMinimumSize(new java.awt.Dimension(200, 200));

        javax.swing.GroupLayout StudentProfilePFPLayout = new javax.swing.GroupLayout(StudentProfilePFP);
        StudentProfilePFP.setLayout(StudentProfilePFPLayout);
        StudentProfilePFPLayout.setHorizontalGroup(
            StudentProfilePFPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 200, Short.MAX_VALUE)
        );
        StudentProfilePFPLayout.setVerticalGroup(
            StudentProfilePFPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 200, Short.MAX_VALUE)
        );

        LeftPanel.add(StudentProfilePFP, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 40, 200, 200));

        StudentIdNamePanel.setMaximumSize(new java.awt.Dimension(200, 80));
        StudentIdNamePanel.setMinimumSize(new java.awt.Dimension(200, 80));
        StudentIdNamePanel.setPreferredSize(new java.awt.Dimension(200, 80));
        StudentIdNamePanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        PStudentIDLabel.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        PStudentIDLabel.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        PStudentIDLabel.setText("Student ID:");
        PStudentIDLabel.setToolTipText("");
        PStudentIDLabel.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);
        StudentIdNamePanel.add(PStudentIDLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 80, -1));

        PStudentNameLabel.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        PStudentNameLabel.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        PStudentNameLabel.setText("Name:");
        PStudentNameLabel.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);
        StudentIdNamePanel.add(PStudentNameLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 30, 80, -1));

        PStudentUsernameLabel.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        PStudentUsernameLabel.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        PStudentUsernameLabel.setText("Username:");
        PStudentUsernameLabel.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);
        StudentIdNamePanel.add(PStudentUsernameLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 60, 80, -1));

        CPStudentIDLabel.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        CPStudentIDLabel.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        CPStudentIDLabel.setText("Student ID");
        CPStudentIDLabel.setToolTipText("");
        CPStudentIDLabel.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);
        StudentIdNamePanel.add(CPStudentIDLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(85, 0, 115, -1));

        CPStudentNameLabel.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        CPStudentNameLabel.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        CPStudentNameLabel.setText("Student Name");
        CPStudentNameLabel.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);
        StudentIdNamePanel.add(CPStudentNameLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(85, 30, 115, -1));

        CPStudentUsernameLabel.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        CPStudentUsernameLabel.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        CPStudentUsernameLabel.setText("Username");
        CPStudentUsernameLabel.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);
        StudentIdNamePanel.add(CPStudentUsernameLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(85, 60, 115, -1));

        LeftPanel.add(StudentIdNamePanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 280, 200, 130));

        StudentInfoTab.add(LeftPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 0, 200, 420));

        RightPanel.setMaximumSize(new java.awt.Dimension(630, 500));
        RightPanel.setMinimumSize(new java.awt.Dimension(630, 500));

        StudentInfoLabel.setMaximumSize(new java.awt.Dimension(10, 10));
        StudentInfoLabel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        PPersonalInfoLabel1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        PPersonalInfoLabel1.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        PPersonalInfoLabel1.setText("Personal Information");
        PPersonalInfoLabel1.setToolTipText("");
        PPersonalInfoLabel1.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);
        StudentInfoLabel.add(PPersonalInfoLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 20, -1, -1));

        PAgeLabel.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        PAgeLabel.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        PAgeLabel.setText("Age:");
        PAgeLabel.setToolTipText("");
        PAgeLabel.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);
        StudentInfoLabel.add(PAgeLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 60, -1, -1));

        PGenderLabel.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        PGenderLabel.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        PGenderLabel.setText("IC:");
        PGenderLabel.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);
        StudentInfoLabel.add(PGenderLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 120, -1, 20));

        PICLabel.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        PICLabel.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        PICLabel.setText("Gender:");
        PICLabel.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);
        StudentInfoLabel.add(PICLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 90, -1, 20));

        PPHLabel.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        PPHLabel.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        PPHLabel.setText("Phone Number:");
        PPHLabel.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);
        StudentInfoLabel.add(PPHLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 60, -1, -1));

        PEmailLabel.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        PEmailLabel.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        PEmailLabel.setText("Email Address:");
        PEmailLabel.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);
        StudentInfoLabel.add(PEmailLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 90, -1, -1));

        PAddressLabel.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        PAddressLabel.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        PAddressLabel.setText("Address:");
        PAddressLabel.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);
        StudentInfoLabel.add(PAddressLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 150, -1, -1));

        PStudentInfoLabel.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        PStudentInfoLabel.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        PStudentInfoLabel.setText("Student Information");
        PStudentInfoLabel.setToolTipText("");
        PStudentInfoLabel.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);
        StudentInfoLabel.add(PStudentInfoLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 220, -1, -1));

        PLevelLabel.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        PLevelLabel.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        PLevelLabel.setText("Level: ");
        PLevelLabel.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);
        StudentInfoLabel.add(PLevelLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 260, -1, -1));

        PEnrolLabel.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        PEnrolLabel.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        PEnrolLabel.setText("Enrolment: ");
        PEnrolLabel.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);
        StudentInfoLabel.add(PEnrolLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 290, -1, -1));

        CPAgeLabel.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        CPAgeLabel.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        CPAgeLabel.setText("-");
        CPAgeLabel.setToolTipText("");
        CPAgeLabel.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);
        StudentInfoLabel.add(CPAgeLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 60, -1, -1));

        CPGenderLabel.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        CPGenderLabel.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        CPGenderLabel.setText("-");
        CPGenderLabel.setToolTipText("");
        CPGenderLabel.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);
        StudentInfoLabel.add(CPGenderLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 90, -1, -1));

        CPICLabel.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        CPICLabel.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        CPICLabel.setText("-");
        CPICLabel.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);
        StudentInfoLabel.add(CPICLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 120, -1, -1));

        CPEmailLabel.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        CPEmailLabel.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        CPEmailLabel.setText("-");
        CPEmailLabel.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);
        StudentInfoLabel.add(CPEmailLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 90, -1, 20));

        CPPHLabel.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        CPPHLabel.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        CPPHLabel.setText("-");
        CPPHLabel.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);
        StudentInfoLabel.add(CPPHLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 60, -1, -1));

        CPAddressLabel.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        CPAddressLabel.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        CPAddressLabel.setText("-");
        CPAddressLabel.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);
        StudentInfoLabel.add(CPAddressLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 150, -1, -1));

        CPLevelLabel.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        CPLevelLabel.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        CPLevelLabel.setText("-");
        CPLevelLabel.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);
        StudentInfoLabel.add(CPLevelLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 260, -1, -1));

        CPEnrolLabel.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        CPEnrolLabel.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        CPEnrolLabel.setText("-");
        CPEnrolLabel.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);
        StudentInfoLabel.add(CPEnrolLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 290, -1, -1));

        jScrollPane1.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_NEVER);
        jScrollPane1.setEnabled(false);

        SubjectTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Subject", "ID", "Teacher"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        SubjectTable.setRowHeight(30);
        SubjectTable.setRowMargin(5);
        jScrollPane1.setViewportView(SubjectTable);
        if (SubjectTable.getColumnModel().getColumnCount() > 0) {
            SubjectTable.getColumnModel().getColumn(0).setResizable(false);
            SubjectTable.getColumnModel().getColumn(0).setPreferredWidth(120);
            SubjectTable.getColumnModel().getColumn(1).setResizable(false);
            SubjectTable.getColumnModel().getColumn(1).setPreferredWidth(50);
            SubjectTable.getColumnModel().getColumn(2).setResizable(false);
            SubjectTable.getColumnModel().getColumn(2).setPreferredWidth(250);
        }

        StudentInfoLabel.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 200, 310, 120));

        PPersonalInfoLabel2.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        PPersonalInfoLabel2.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        PPersonalInfoLabel2.setText("Contact Information");
        PPersonalInfoLabel2.setToolTipText("");
        PPersonalInfoLabel2.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);
        StudentInfoLabel.add(PPersonalInfoLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 20, 310, -1));

        PPersonalInfoLabel3.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        PPersonalInfoLabel3.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        PPersonalInfoLabel3.setText("Enrolled Subjects");
        PPersonalInfoLabel3.setToolTipText("");
        PPersonalInfoLabel3.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);
        StudentInfoLabel.add(PPersonalInfoLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 160, 310, -1));

        javax.swing.GroupLayout RightPanelLayout = new javax.swing.GroupLayout(RightPanel);
        RightPanel.setLayout(RightPanelLayout);
        RightPanelLayout.setHorizontalGroup(
            RightPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, RightPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(StudentInfoLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 614, Short.MAX_VALUE))
        );
        RightPanelLayout.setVerticalGroup(
            RightPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(RightPanelLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(StudentInfoLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        StudentInfoTab.add(RightPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(277, 0, 620, 430));

        StudentProfileTabbedPane.addTab("Student Information", StudentInfoTab);

        StudentPaymentTab.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        StudentPaymentHistory.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null}
            },
            new String [] {
                "Year", "Month(s)", "Subject(s)", "Amount", "Plan", "Method", "Date"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        StudentPaymentHistory.setRowHeight(30);
        StudentPaymentHistory.setRowMargin(5);
        StudentPaymentHistoryScrollPane.setViewportView(StudentPaymentHistory);
        if (StudentPaymentHistory.getColumnModel().getColumnCount() > 0) {
            StudentPaymentHistory.getColumnModel().getColumn(0).setPreferredWidth(50);
            StudentPaymentHistory.getColumnModel().getColumn(1).setPreferredWidth(200);
            StudentPaymentHistory.getColumnModel().getColumn(2).setPreferredWidth(200);
            StudentPaymentHistory.getColumnModel().getColumn(3).setPreferredWidth(80);
            StudentPaymentHistory.getColumnModel().getColumn(4).setPreferredWidth(100);
            StudentPaymentHistory.getColumnModel().getColumn(5).setPreferredWidth(100);
            StudentPaymentHistory.getColumnModel().getColumn(6).setPreferredWidth(100);
        }

        StudentPaymentTab.add(StudentPaymentHistoryScrollPane, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 30, 870, 380));

        StudentProfileBackButton1.setText("Back");
        StudentProfileBackButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                StudentProfileBackButton1ActionPerformed(evt);
            }
        });
        StudentPaymentTab.add(StudentProfileBackButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(830, 440, 70, 35));

        StudentProfileTabbedPane.addTab("Payment History", StudentPaymentTab);

        StudentProfilePage.add(StudentProfileTabbedPane, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 100, 930, 550));

        jPanel2.setBackground(new java.awt.Color(184, 186, 191));
        jPanel2.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        StudentManagementTitle.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        StudentManagementTitle.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        StudentManagementTitle.setText("Student Profile");
        StudentManagementTitle.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(StudentManagementTitle, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 926, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addComponent(StudentManagementTitle)
                .addContainerGap(33, Short.MAX_VALUE))
        );

        StudentProfilePage.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 930, 100));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 930, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(StudentProfilePage, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 650, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(StudentProfilePage, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void EditStudentInfoButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EditStudentInfoButtonActionPerformed
        parent.switchPanelParameters("sprofileedit", saveselectedstudent, saveselectedlogin);
    }//GEN-LAST:event_EditStudentInfoButtonActionPerformed

    private void ChangeStudentLoginButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ChangeStudentLoginButtonActionPerformed
        PopupLoginCredentials popup = new PopupLoginCredentials(saveselectedlogin);
        JButton[] options = {popup.getLCOKButton(), popup.getLCCancelButton()};
        JButton okbutton = options[0];
        
        while (true) {
            JOptionPane.showOptionDialog(this, popup, "Change Login Credentials", JOptionPane.DEFAULT_OPTION, JOptionPane.PLAIN_MESSAGE, null, options, okbutton);
            
            if (popup.getLCChoice() == 0) {
                if (GeneralMethods.ValidateUsername(saveselectedlogin.get(0).trim(), popup.getNewUsername().trim())) {
                    int choice2 = JOptionPane.showConfirmDialog(this, "Confirm changes to student login credentials?", "Login Credentials Change Confirmation", JOptionPane.YES_NO_OPTION);
                    if (choice2 == JOptionPane.OK_OPTION) {
                        String newusername = popup.getNewUsername();
                        String newpassword = popup.getNewPassword();
                        GeneralMethods.SaveNewLogin(saveselectedstudent.getStudentid(), newusername, newpassword);
                        CPStudentUsernameLabel.setText(newusername);
                        saveselectedlogin.set(0, newusername);
                        saveselectedlogin.set(1, newpassword);
                        popup.setUsername(newusername);
                        popup.setPassword(newpassword);
                        revalidate();
                        repaint();
                        break;
                    }
                } else {
                    popup.getUsernameField().setText(saveselectedlogin.get(0));
                }
            } else {
                break;
            }
        } 

        
            
    }//GEN-LAST:event_ChangeStudentLoginButtonActionPerformed

    private void StudentProfileBackButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_StudentProfileBackButtonActionPerformed
        parent.switchPanel("student");
    }//GEN-LAST:event_StudentProfileBackButtonActionPerformed

    private void ResetPFPButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ResetPFPButtonActionPerformed
        GeneralMethods.ResetPFP(this, saveselectedstudent.getStudentid());
        GeneralMethods.LoadPFP(StudentProfilePFP, "Profile Pictures/"+ saveselectedstudent.getStudentid() +".jpg");
    }//GEN-LAST:event_ResetPFPButtonActionPerformed

    private void DeleteStudentButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DeleteStudentButtonActionPerformed
        String selectedsid = saveselectedstudent.getStudentid();
        int choice = JOptionPane.showConfirmDialog(this, "Delete student " + saveselectedstudent.getStudentname() + " (" + selectedsid + ")?", "Deletion Confirmation", JOptionPane.YES_NO_OPTION);
        if (choice == JOptionPane.YES_OPTION) {
            StudentMethods.DeleteStudent(selectedsid);
            JOptionPane.showMessageDialog(null, "Student successfully deleted.");
            parent.switchPanel("student");
        } else {
            return;
        }

    }//GEN-LAST:event_DeleteStudentButtonActionPerformed

    private void StudentProfileBackButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_StudentProfileBackButton1ActionPerformed
        parent.switchPanel("student");
    }//GEN-LAST:event_StudentProfileBackButton1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel CPAddressLabel;
    private javax.swing.JLabel CPAgeLabel;
    private javax.swing.JLabel CPEmailLabel;
    private javax.swing.JLabel CPEnrolLabel;
    private javax.swing.JLabel CPGenderLabel;
    private javax.swing.JLabel CPICLabel;
    private javax.swing.JLabel CPLevelLabel;
    private javax.swing.JLabel CPPHLabel;
    private javax.swing.JLabel CPStudentIDLabel;
    private javax.swing.JLabel CPStudentNameLabel;
    private javax.swing.JLabel CPStudentUsernameLabel;
    private javax.swing.JButton ChangeStudentLoginButton;
    private javax.swing.JButton DeleteStudentButton;
    private javax.swing.JButton EditStudentInfoButton;
    private javax.swing.JPanel LeftPanel;
    private javax.swing.JLabel PAddressLabel;
    private javax.swing.JLabel PAgeLabel;
    private javax.swing.JLabel PEmailLabel;
    private javax.swing.JLabel PEnrolLabel;
    private javax.swing.JLabel PGenderLabel;
    private javax.swing.JLabel PICLabel;
    private javax.swing.JLabel PLevelLabel;
    private javax.swing.JLabel PPHLabel;
    private javax.swing.JLabel PPersonalInfoLabel1;
    private javax.swing.JLabel PPersonalInfoLabel2;
    private javax.swing.JLabel PPersonalInfoLabel3;
    private javax.swing.JLabel PStudentIDLabel;
    private javax.swing.JLabel PStudentInfoLabel;
    private javax.swing.JLabel PStudentNameLabel;
    private javax.swing.JLabel PStudentUsernameLabel;
    private javax.swing.JButton ResetPFPButton;
    private javax.swing.JPanel RightPanel;
    private javax.swing.JPanel StudentIdNamePanel;
    private javax.swing.JPanel StudentInfoLabel;
    private javax.swing.JPanel StudentInfoTab;
    private javax.swing.JLabel StudentManagementTitle;
    private javax.swing.JTable StudentPaymentHistory;
    private javax.swing.JScrollPane StudentPaymentHistoryScrollPane;
    private javax.swing.JPanel StudentPaymentTab;
    private javax.swing.JButton StudentProfileBackButton;
    private javax.swing.JButton StudentProfileBackButton1;
    private AdminFrontend.ImagePanel StudentProfilePFP;
    private javax.swing.JPanel StudentProfilePage;
    private javax.swing.JTabbedPane StudentProfileTabbedPane;
    private javax.swing.JTable SubjectTable;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    // End of variables declaration//GEN-END:variables
}
