/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package AdminFrontend;

import AdminBackend.GeneralMethods;
import AdminModels.Student;
import AdminBackend.StudentMethods;
import java.util.List;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author User
 */
public class AStudentMenuPanel extends javax.swing.JPanel {

    private final AdminFrame parent;
    DefaultTableModel studenttablemodel;
    
    /**
     * Creates new form AStudentMenuPanel
     */
    
    public AStudentMenuPanel(AdminFrame parent) {
        this.parent = parent;
        initComponents();
        this.studenttablemodel = (DefaultTableModel) StudentList.getModel();
        StudentMethods.PopulateStudentList(studenttablemodel);
    }

    public JTable getStudentList() {
        return StudentList;
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        StudentMenuPage = new javax.swing.JPanel();
        StudentScrollPanel = new javax.swing.JScrollPane();
        StudentList = new javax.swing.JTable();
        RegisterStudentButton = new javax.swing.JButton();
        StudentMenuBackButton = new javax.swing.JButton();
        SubjectEnrollmentRequestsButton = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        StudentManagementTitle = new javax.swing.JLabel();

        StudentMenuPage.setMaximumSize(new java.awt.Dimension(930, 650));
        StudentMenuPage.setMinimumSize(new java.awt.Dimension(930, 650));
        StudentMenuPage.setPreferredSize(new java.awt.Dimension(930, 650));
        StudentMenuPage.setRequestFocusEnabled(false);
        StudentMenuPage.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        StudentList.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        StudentList.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Student ID", "Student Name", "Level"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        StudentList.setMaximumSize(null);
        StudentList.setMinimumSize(null);
        StudentList.setRowHeight(30);
        StudentList.setRowMargin(5);
        StudentList.getTableHeader().setResizingAllowed(false);
        StudentList.getTableHeader().setReorderingAllowed(false);
        StudentList.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                StudentListMouseClicked(evt);
            }
        });
        StudentList.addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentShown(java.awt.event.ComponentEvent evt) {
                StudentListComponentShown(evt);
            }
        });
        StudentScrollPanel.setViewportView(StudentList);
        if (StudentList.getColumnModel().getColumnCount() > 0) {
            StudentList.getColumnModel().getColumn(0).setPreferredWidth(10);
            StudentList.getColumnModel().getColumn(1).setPreferredWidth(400);
            StudentList.getColumnModel().getColumn(2).setPreferredWidth(100);
        }

        StudentMenuPage.add(StudentScrollPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 140, 870, 390));

        RegisterStudentButton.setText("Register New Student");
        RegisterStudentButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RegisterStudentButtonActionPerformed(evt);
            }
        });
        StudentMenuPage.add(RegisterStudentButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 565, 170, 35));

        StudentMenuBackButton.setText("Back");
        StudentMenuBackButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                StudentMenuBackButtonActionPerformed(evt);
            }
        });
        StudentMenuPage.add(StudentMenuBackButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(830, 565, 70, 35));

        SubjectEnrollmentRequestsButton.setText("Subject Enrollment Requests");
        SubjectEnrollmentRequestsButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SubjectEnrollmentRequestsButtonActionPerformed(evt);
            }
        });
        StudentMenuPage.add(SubjectEnrollmentRequestsButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 565, 200, 35));

        jPanel2.setBackground(new java.awt.Color(184, 186, 191));
        jPanel2.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        StudentManagementTitle.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        StudentManagementTitle.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        StudentManagementTitle.setText("Student Management");
        StudentManagementTitle.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(StudentManagementTitle, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 926, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addComponent(StudentManagementTitle)
                .addContainerGap(33, Short.MAX_VALUE))
        );

        StudentMenuPage.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 930, 100));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 930, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(StudentMenuPage, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 650, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(StudentMenuPage, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void RegisterStudentButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RegisterStudentButtonActionPerformed
        parent.switchPanel("sregister");
    }//GEN-LAST:event_RegisterStudentButtonActionPerformed

    private void StudentMenuBackButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_StudentMenuBackButtonActionPerformed
        parent.switchPanel("admin");
    }//GEN-LAST:event_StudentMenuBackButtonActionPerformed

    private void StudentListMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_StudentListMouseClicked
        String selectedsid = studenttablemodel.getValueAt(StudentList.getSelectedRow(), 0).toString();
        Student selectedstudent = StudentMethods.GetStudentByID(selectedsid);
        List<String> creds = GeneralMethods.GetLoginCreds(selectedsid);
        
        parent.switchPanelParameters("sprofile", selectedstudent, creds);
    }//GEN-LAST:event_StudentListMouseClicked

    private void StudentListComponentShown(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_StudentListComponentShown
        DefaultTableModel model = parent.getStudentTableModel();
        StudentMethods.PopulateStudentList(model);
    }//GEN-LAST:event_StudentListComponentShown

    private void SubjectEnrollmentRequestsButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SubjectEnrollmentRequestsButtonActionPerformed
        parent.switchPanel("srequest");
    }//GEN-LAST:event_SubjectEnrollmentRequestsButtonActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton RegisterStudentButton;
    private javax.swing.JTable StudentList;
    private javax.swing.JLabel StudentManagementTitle;
    private javax.swing.JButton StudentMenuBackButton;
    private javax.swing.JPanel StudentMenuPage;
    private javax.swing.JScrollPane StudentScrollPanel;
    private javax.swing.JButton SubjectEnrollmentRequestsButton;
    private javax.swing.JPanel jPanel2;
    // End of variables declaration//GEN-END:variables
}
