/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package AdminFrontend;

import AdminBackend.StudentMethods;
import java.io.IOException;
import javax.swing.JOptionPane;
import javax.swing.ListSelectionModel;
import javax.swing.event.ListSelectionEvent;
import javax.swing.event.ListSelectionListener;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author User
 */
public class AStudentSubjectRequest extends javax.swing.JPanel {

    private final AdminFrame parent;
    DefaultTableModel pendingrequestsmodel;
    DefaultTableModel approvedrequestsmodel;
    
    /**
     * Creates new form AStudentMenuPanel
     */
    
    public AStudentSubjectRequest(AdminFrame parent) {
        this.parent = parent;
        initComponents();
        this.pendingrequestsmodel = (DefaultTableModel) PendingRequests.getModel();
        this.approvedrequestsmodel = (DefaultTableModel) ApprovedRequests.getModel();
        
        StudentMethods.PopulatePendingRequests(pendingrequestsmodel);
        StudentMethods.PopulateApprovedRequests(approvedrequestsmodel);
        
        // Selection listener for Payment History JTable (for receipt generation function)
        ApproveRequestButton.setEnabled(false);
        
        ListSelectionModel selectionmodel = PendingRequests.getSelectionModel();
        selectionmodel.setSelectionMode(ListSelectionModel.SINGLE_SELECTION);

        selectionmodel.addListSelectionListener(new ListSelectionListener() {
            @Override
            public void valueChanged(ListSelectionEvent event) {
                // Ignore adjusting events
                if (event.getValueIsAdjusting()) {
                    return;
                }

                int selectedRow = PendingRequests.getSelectedRow();

                if (selectedRow >= 0) {
                    ApproveRequestButton.setEnabled(true);
                } else {
                    ApproveRequestButton.setEnabled(false);
                }
            }
        });
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        SubjectEnrollmentRequestsPanel = new javax.swing.JPanel();
        EnrollmentRequestsPanel = new javax.swing.JTabbedPane();
        PendingRequestsTab = new javax.swing.JPanel();
        ApproveRequestButton = new javax.swing.JButton();
        PaymentBackButton = new javax.swing.JButton();
        PendingRequestsTableScrollPane = new javax.swing.JScrollPane();
        PendingRequests = new javax.swing.JTable();
        ApprovedRequestsTab = new javax.swing.JPanel();
        ApprovedRequestsTableScrollPane = new javax.swing.JScrollPane();
        ApprovedRequests = new javax.swing.JTable();
        PaymentBackButton2 = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        StudentManagementTitle = new javax.swing.JLabel();

        SubjectEnrollmentRequestsPanel.setMaximumSize(new java.awt.Dimension(930, 650));
        SubjectEnrollmentRequestsPanel.setMinimumSize(new java.awt.Dimension(930, 650));
        SubjectEnrollmentRequestsPanel.setPreferredSize(new java.awt.Dimension(930, 650));
        SubjectEnrollmentRequestsPanel.setRequestFocusEnabled(false);
        SubjectEnrollmentRequestsPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        EnrollmentRequestsPanel.setMaximumSize(new java.awt.Dimension(850, 500));
        EnrollmentRequestsPanel.setMinimumSize(new java.awt.Dimension(850, 500));
        EnrollmentRequestsPanel.setPreferredSize(new java.awt.Dimension(850, 500));

        PendingRequestsTab.setMaximumSize(new java.awt.Dimension(200, 200));
        PendingRequestsTab.setMinimumSize(new java.awt.Dimension(200, 200));
        PendingRequestsTab.setPreferredSize(new java.awt.Dimension(200, 200));
        PendingRequestsTab.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        ApproveRequestButton.setText("Approve Request");
        ApproveRequestButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ApproveRequestButtonActionPerformed(evt);
            }
        });
        PendingRequestsTab.add(ApproveRequestButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 435, 140, 35));

        PaymentBackButton.setText("Back");
        PaymentBackButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PaymentBackButtonActionPerformed(evt);
            }
        });
        PendingRequestsTab.add(PaymentBackButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(830, 435, 70, 35));

        PendingRequests.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        PendingRequests.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Name", "Subject", "Reason", "Date"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        PendingRequests.setRowHeight(30);
        PendingRequests.setRowMargin(5);
        PendingRequests.getTableHeader().setResizingAllowed(false);
        PendingRequests.getTableHeader().setReorderingAllowed(false);
        PendingRequests.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                PendingRequestsMouseClicked(evt);
            }
        });
        PendingRequests.addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentShown(java.awt.event.ComponentEvent evt) {
                PendingRequestsComponentShown(evt);
            }
        });
        PendingRequests.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                PendingRequestsPropertyChange(evt);
            }
        });
        PendingRequestsTableScrollPane.setViewportView(PendingRequests);
        if (PendingRequests.getColumnModel().getColumnCount() > 0) {
            PendingRequests.getColumnModel().getColumn(0).setPreferredWidth(50);
            PendingRequests.getColumnModel().getColumn(1).setPreferredWidth(150);
            PendingRequests.getColumnModel().getColumn(2).setPreferredWidth(120);
            PendingRequests.getColumnModel().getColumn(3).setPreferredWidth(500);
            PendingRequests.getColumnModel().getColumn(4).setPreferredWidth(100);
        }

        PendingRequestsTab.add(PendingRequestsTableScrollPane, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 35, 870, 370));

        EnrollmentRequestsPanel.addTab("Pending Requests", PendingRequestsTab);

        ApprovedRequestsTab.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        ApprovedRequests.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        ApprovedRequests.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Name", "Subject", "Reason", "Date"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        ApprovedRequests.setRowHeight(30);
        ApprovedRequests.setRowMargin(5);
        ApprovedRequests.getTableHeader().setResizingAllowed(false);
        ApprovedRequests.getTableHeader().setReorderingAllowed(false);
        ApprovedRequests.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ApprovedRequestsMouseClicked(evt);
            }
        });
        ApprovedRequests.addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentShown(java.awt.event.ComponentEvent evt) {
                ApprovedRequestsComponentShown(evt);
            }
        });
        ApprovedRequests.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                ApprovedRequestsPropertyChange(evt);
            }
        });
        ApprovedRequestsTableScrollPane.setViewportView(ApprovedRequests);
        if (ApprovedRequests.getColumnModel().getColumnCount() > 0) {
            ApprovedRequests.getColumnModel().getColumn(0).setPreferredWidth(50);
            ApprovedRequests.getColumnModel().getColumn(1).setPreferredWidth(150);
            ApprovedRequests.getColumnModel().getColumn(2).setPreferredWidth(120);
            ApprovedRequests.getColumnModel().getColumn(3).setPreferredWidth(500);
            ApprovedRequests.getColumnModel().getColumn(4).setPreferredWidth(100);
        }

        ApprovedRequestsTab.add(ApprovedRequestsTableScrollPane, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 35, 870, 370));

        PaymentBackButton2.setText("Back");
        PaymentBackButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PaymentBackButton2ActionPerformed(evt);
            }
        });
        ApprovedRequestsTab.add(PaymentBackButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(830, 435, 70, 35));

        EnrollmentRequestsPanel.addTab("Approved Requests", ApprovedRequestsTab);

        SubjectEnrollmentRequestsPanel.add(EnrollmentRequestsPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 100, 930, 550));

        jPanel2.setBackground(new java.awt.Color(184, 186, 191));
        jPanel2.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        StudentManagementTitle.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        StudentManagementTitle.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        StudentManagementTitle.setText("Subject Enrollment Requests");
        StudentManagementTitle.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(StudentManagementTitle, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 926, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addComponent(StudentManagementTitle)
                .addContainerGap(33, Short.MAX_VALUE))
        );

        SubjectEnrollmentRequestsPanel.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 930, 100));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 930, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(SubjectEnrollmentRequestsPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 650, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(SubjectEnrollmentRequestsPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void ApproveRequestButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ApproveRequestButtonActionPerformed
        int row = PendingRequests.getSelectedRow();
        String selectedstudentid = (String) PendingRequests.getValueAt(row, 0);
        
        try {
            StudentMethods.ApproveRequest(selectedstudentid);
            JOptionPane.showMessageDialog(this, "Subject enrollment request marked as approved.\nPlease update subject enrollment in student profile.", "Successful Enrollment Request Approval", JOptionPane.PLAIN_MESSAGE);
            StudentMethods.PopulatePendingRequests(pendingrequestsmodel);
            StudentMethods.PopulateApprovedRequests(approvedrequestsmodel);
        } catch (IOException ex) {
            ex.printStackTrace();
        }
    }//GEN-LAST:event_ApproveRequestButtonActionPerformed

    private void PaymentBackButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PaymentBackButtonActionPerformed
        parent.switchPanel("student");
    }//GEN-LAST:event_PaymentBackButtonActionPerformed

    private void PendingRequestsMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_PendingRequestsMouseClicked

    }//GEN-LAST:event_PendingRequestsMouseClicked

    private void PendingRequestsComponentShown(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_PendingRequestsComponentShown

    }//GEN-LAST:event_PendingRequestsComponentShown

    private void PendingRequestsPropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_PendingRequestsPropertyChange

    }//GEN-LAST:event_PendingRequestsPropertyChange

    private void PaymentBackButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PaymentBackButton2ActionPerformed
        parent.switchPanel("student");
    }//GEN-LAST:event_PaymentBackButton2ActionPerformed

    private void ApprovedRequestsMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ApprovedRequestsMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_ApprovedRequestsMouseClicked

    private void ApprovedRequestsComponentShown(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_ApprovedRequestsComponentShown
        // TODO add your handling code here:
    }//GEN-LAST:event_ApprovedRequestsComponentShown

    private void ApprovedRequestsPropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_ApprovedRequestsPropertyChange
        // TODO add your handling code here:
    }//GEN-LAST:event_ApprovedRequestsPropertyChange

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton ApproveRequestButton;
    private javax.swing.JTable ApprovedRequests;
    private javax.swing.JPanel ApprovedRequestsTab;
    private javax.swing.JScrollPane ApprovedRequestsTableScrollPane;
    private javax.swing.JTabbedPane EnrollmentRequestsPanel;
    private javax.swing.JButton PaymentBackButton;
    private javax.swing.JButton PaymentBackButton2;
    private javax.swing.JTable PendingRequests;
    private javax.swing.JPanel PendingRequestsTab;
    private javax.swing.JScrollPane PendingRequestsTableScrollPane;
    private javax.swing.JLabel StudentManagementTitle;
    private javax.swing.JPanel SubjectEnrollmentRequestsPanel;
    private javax.swing.JPanel jPanel2;
    // End of variables declaration//GEN-END:variables
}
