/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package AdminFrontend;

import AdminBackend.GeneralMethods;
import AdminBackend.TutorMethods;
import AdminModels.Tutor;
import javax.swing.JOptionPane;

/**
 *
 * @author User
 */
public class ATutorRegisterPanel extends javax.swing.JPanel {
    
    private final AdminFrame parent;
    
    /**
     * Creates new form ATutorRegisterPanel
     */
    public ATutorRegisterPanel(AdminFrame parent) {
        this.parent = parent;
        initComponents();
        ResetTutorRegister();   
        GeneralMethods.LoadPFP(NewTutorPFP, "Profile Pictures/Default.jpg");
        
        NameField.getDocument().addDocumentListener(GeneralMethods.MakeSimpleDocumentListener(() -> CheckForEmptyFields()));
        PHField.getDocument().addDocumentListener(GeneralMethods.MakeSimpleDocumentListener(() -> CheckForEmptyFields()));
        EmailField.getDocument().addDocumentListener(GeneralMethods.MakeSimpleDocumentListener(() -> CheckForEmptyFields()));
        AddressField.getDocument().addDocumentListener(GeneralMethods.MakeSimpleDocumentListener(() -> CheckForEmptyFields()));
    }
    
    private void ResetTutorRegister() {
        String newtutorid = TutorMethods.GetNewTutorID();
        int newtutoridnum = Integer.parseInt(newtutorid.substring(1));
        String newusername = "tutor" + newtutoridnum;
        String newpassword = "tpassword" + newtutoridnum;
        
        NewTutorIDField.setText(newtutorid);
        TempUNField.setText(newusername);
        TempPWField.setText(newpassword);
        
        NameField.setText("");
        GenderField.setSelectedIndex(0);
        AddressField.setText("");
        PHField.setText("");
        EmailField.setText("");
        LevelField.setSelectedIndex(0);
        SubjectField.setSelectedIndex(0);
    }
    
    private boolean ValidateAllInputs() {
        // Validate Name
        String name = NameField.getText().trim();
        if (name.isEmpty() || !name.matches("[a-zA-Z ]+")) {
            return false;
        }

        // Validate Phone Number
        String ph = PHField.getText().trim();
        if (ph.isEmpty() || ph.length() != 9 || !ph.matches("\\d+")) {
            return false;
        }

        // Validate Email
        String email = EmailField.getText().trim();
        if (email.isEmpty() || !email.matches("^[\\w.-]+@[\\w.-]+\\.\\w+$")) {
            return false;
        }

        // Validate Address
        String address = AddressField.getText().trim();
        if (address.isEmpty() || !address.matches("[a-zA-Z0-9 ]+")) {
            return false;
        }

        return true; // All validations passed
    }
    
    private void CheckForEmptyFields() {
        boolean valid =
        !NameField.getText().trim().isEmpty() &&
        !PHField.getText().trim().isEmpty() &&
        !EmailField.getText().trim().isEmpty() &&
        !AddressField.getText().trim().isEmpty();

        RegisterButton.setEnabled(valid);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        RegisterTutorPage = new javax.swing.JPanel();
        TutorRegisterBackButton = new javax.swing.JButton();
        RegisterButton = new javax.swing.JButton();
        TutorInfoLabel = new javax.swing.JPanel();
        PersonalContactInfoLabel = new javax.swing.JLabel();
        NameLabel = new javax.swing.JLabel();
        GenderLabel = new javax.swing.JLabel();
        PHLabel = new javax.swing.JLabel();
        PHFormatLabel = new javax.swing.JLabel();
        EmailLabel = new javax.swing.JLabel();
        AddressLabel = new javax.swing.JLabel();
        NameField = new javax.swing.JTextField();
        GenderField = new javax.swing.JComboBox<>();
        PHField = new javax.swing.JTextField();
        EmailField = new javax.swing.JTextField();
        AddressField = new javax.swing.JTextField();
        StudentIdNamePanel = new javax.swing.JPanel();
        TutorIDLabel = new javax.swing.JLabel();
        TempUNLabel = new javax.swing.JLabel();
        TempPWLabel = new javax.swing.JLabel();
        NewTutorIDField = new javax.swing.JLabel();
        TempUNField = new javax.swing.JLabel();
        TempPWField = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        PStudentInfoLabel2 = new javax.swing.JLabel();
        LevelLabel = new javax.swing.JLabel();
        SubjectLabel = new javax.swing.JLabel();
        LevelField = new javax.swing.JComboBox<>();
        SubjectField = new javax.swing.JComboBox<>();
        NewTutorPFP = new AdminFrontend.ImagePanel();
        jPanel2 = new javax.swing.JPanel();
        StudentManagementTitle = new javax.swing.JLabel();

        setMaximumSize(new java.awt.Dimension(930, 650));
        setMinimumSize(new java.awt.Dimension(930, 650));
        setPreferredSize(new java.awt.Dimension(930, 650));

        RegisterTutorPage.setMaximumSize(new java.awt.Dimension(930, 650));
        RegisterTutorPage.setMinimumSize(new java.awt.Dimension(930, 650));
        RegisterTutorPage.setPreferredSize(new java.awt.Dimension(930, 650));
        RegisterTutorPage.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        TutorRegisterBackButton.setText("Back");
        TutorRegisterBackButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TutorRegisterBackButtonActionPerformed(evt);
            }
        });
        RegisterTutorPage.add(TutorRegisterBackButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(830, 565, 70, 35));

        RegisterButton.setText("Register");
        RegisterButton.setEnabled(false);
        RegisterButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RegisterButtonActionPerformed(evt);
            }
        });
        RegisterTutorPage.add(RegisterButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(730, 565, 80, 35));

        TutorInfoLabel.setMaximumSize(new java.awt.Dimension(10, 10));
        TutorInfoLabel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        PersonalContactInfoLabel.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        PersonalContactInfoLabel.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        PersonalContactInfoLabel.setText("Personal & Contact Information");
        PersonalContactInfoLabel.setToolTipText("");
        PersonalContactInfoLabel.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);
        TutorInfoLabel.add(PersonalContactInfoLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 140, -1, 40));

        NameLabel.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        NameLabel.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        NameLabel.setText("Name:");
        NameLabel.setToolTipText("");
        NameLabel.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);
        TutorInfoLabel.add(NameLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 190, -1, 30));

        GenderLabel.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        GenderLabel.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        GenderLabel.setText("Gender:");
        GenderLabel.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);
        TutorInfoLabel.add(GenderLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 230, -1, 30));

        PHLabel.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        PHLabel.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        PHLabel.setText("Phone Number:");
        PHLabel.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);
        TutorInfoLabel.add(PHLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 310, -1, 30));

        PHFormatLabel.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        PHFormatLabel.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        PHFormatLabel.setText("+60 ");
        PHFormatLabel.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);
        TutorInfoLabel.add(PHFormatLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 310, 30, 30));

        EmailLabel.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        EmailLabel.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        EmailLabel.setText("Email Address:");
        EmailLabel.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);
        TutorInfoLabel.add(EmailLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 350, -1, 30));

        AddressLabel.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        AddressLabel.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        AddressLabel.setText("Address:");
        AddressLabel.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);
        TutorInfoLabel.add(AddressLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 270, -1, 30));

        NameField.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                NameFieldFocusLost(evt);
            }
        });
        NameField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NameFieldActionPerformed(evt);
            }
        });
        TutorInfoLabel.add(NameField, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 190, 330, 30));

        GenderField.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Male", "Female" }));
        GenderField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                GenderFieldActionPerformed(evt);
            }
        });
        TutorInfoLabel.add(GenderField, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 230, 100, 30));

        PHField.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                PHFieldFocusLost(evt);
            }
        });
        TutorInfoLabel.add(PHField, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 310, 300, 30));

        EmailField.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                EmailFieldFocusLost(evt);
            }
        });
        EmailField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EmailFieldActionPerformed(evt);
            }
        });
        TutorInfoLabel.add(EmailField, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 350, 330, 30));

        AddressField.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                AddressFieldFocusLost(evt);
            }
        });
        TutorInfoLabel.add(AddressField, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 270, 330, 30));

        StudentIdNamePanel.setMaximumSize(new java.awt.Dimension(200, 80));
        StudentIdNamePanel.setMinimumSize(new java.awt.Dimension(200, 80));
        StudentIdNamePanel.setPreferredSize(new java.awt.Dimension(200, 80));
        StudentIdNamePanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        TutorIDLabel.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        TutorIDLabel.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        TutorIDLabel.setText("Tutor ID:");
        TutorIDLabel.setToolTipText("");
        TutorIDLabel.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);
        StudentIdNamePanel.add(TutorIDLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 10, 160, -1));

        TempUNLabel.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        TempUNLabel.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        TempUNLabel.setText("Temporary Username:");
        TempUNLabel.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);
        StudentIdNamePanel.add(TempUNLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 40, 160, -1));

        TempPWLabel.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        TempPWLabel.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        TempPWLabel.setText("Temporary Password:");
        TempPWLabel.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);
        StudentIdNamePanel.add(TempPWLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 70, 160, -1));

        NewTutorIDField.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        NewTutorIDField.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        NewTutorIDField.setText("Tutor ID");
        NewTutorIDField.setToolTipText("");
        NewTutorIDField.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);
        StudentIdNamePanel.add(NewTutorIDField, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 10, 110, -1));

        TempUNField.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        TempUNField.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        TempUNField.setText("Username");
        TempUNField.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);
        StudentIdNamePanel.add(TempUNField, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 40, 110, -1));

        TempPWField.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        TempPWField.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        TempPWField.setText("Password");
        TempPWField.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);
        StudentIdNamePanel.add(TempPWField, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 70, 110, -1));

        TutorInfoLabel.add(StudentIdNamePanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 6, 320, 100));
        TutorInfoLabel.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 120, 830, 10));

        PStudentInfoLabel2.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        PStudentInfoLabel2.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        PStudentInfoLabel2.setText("Tutor Information");
        PStudentInfoLabel2.setToolTipText("");
        PStudentInfoLabel2.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);
        TutorInfoLabel.add(PStudentInfoLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 140, -1, 40));

        LevelLabel.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        LevelLabel.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        LevelLabel.setText("Level: ");
        LevelLabel.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);
        TutorInfoLabel.add(LevelLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 190, -1, 30));

        SubjectLabel.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        SubjectLabel.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        SubjectLabel.setText("Subject:");
        SubjectLabel.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);
        TutorInfoLabel.add(SubjectLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 240, -1, 30));

        LevelField.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Form 1", "Form 2", "Form 3", "Form 4", "Form 5" }));
        LevelField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LevelFieldActionPerformed(evt);
            }
        });
        TutorInfoLabel.add(LevelField, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 190, 150, 30));

        SubjectField.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "English", "Mathematics", "Science" }));
        SubjectField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SubjectFieldActionPerformed(evt);
            }
        });
        TutorInfoLabel.add(SubjectField, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 240, 150, 30));

        javax.swing.GroupLayout NewTutorPFPLayout = new javax.swing.GroupLayout(NewTutorPFP);
        NewTutorPFP.setLayout(NewTutorPFPLayout);
        NewTutorPFPLayout.setHorizontalGroup(
            NewTutorPFPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        NewTutorPFPLayout.setVerticalGroup(
            NewTutorPFPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        TutorInfoLabel.add(NewTutorPFP, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 6, 100, 100));

        RegisterTutorPage.add(TutorInfoLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 110, 830, 450));

        jPanel2.setBackground(new java.awt.Color(184, 186, 191));
        jPanel2.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        StudentManagementTitle.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        StudentManagementTitle.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        StudentManagementTitle.setText("Tutor Registration");
        StudentManagementTitle.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(StudentManagementTitle, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 926, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addComponent(StudentManagementTitle)
                .addContainerGap(33, Short.MAX_VALUE))
        );

        RegisterTutorPage.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 930, 100));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(RegisterTutorPage, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(RegisterTutorPage, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void TutorRegisterBackButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TutorRegisterBackButtonActionPerformed
        parent.switchPanel("tutor");
    }//GEN-LAST:event_TutorRegisterBackButtonActionPerformed

    private void EmailFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EmailFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_EmailFieldActionPerformed

    private void RegisterButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RegisterButtonActionPerformed
        if (!ValidateAllInputs()) return;
        
        String newtutorid = NewTutorIDField.getText();
        String newtutorlevel = (String) LevelField.getSelectedItem();
        String newtutorname = GeneralMethods.Capitalize(NameField.getText());
        String newtutorgender = (String) GenderField.getSelectedItem();
        String newtutoraddress = GeneralMethods.Capitalize(AddressField.getText());
        String newtutorsubject = (String) SubjectField.getSelectedItem();
        String newtutorph = "+60" + PHField.getText();
        String newtutoremail = EmailField.getText();
        
        if (TutorMethods.ValidateTutor(newtutorid, newtutorname, newtutorph, newtutoremail)) {
            Tutor newtutor = new Tutor(newtutorid, newtutorlevel, newtutorname, newtutorgender, newtutoraddress, newtutorsubject, newtutorph, newtutoremail);

            TutorMethods.SaveNewTutor(newtutor);
            GeneralMethods.SaveNewLogin(newtutorid, TempUNField.getText(), TempPWField.getText());
            JOptionPane.showMessageDialog(null, "Tutor successfully registered!");

            parent.switchPanel("tutor");
            ResetTutorRegister();
        }
        
    }//GEN-LAST:event_RegisterButtonActionPerformed

    private void NameFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NameFieldActionPerformed

    }//GEN-LAST:event_NameFieldActionPerformed

    private void GenderFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_GenderFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_GenderFieldActionPerformed

    private void NameFieldFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_NameFieldFocusLost
        String field = NameField.getText().trim();
        if (field.isEmpty()) return;
        GeneralMethods.InputValidation(NameField, null, 1, Integer.MAX_VALUE, "[a-zA-Z ]+", "Invalid name entered.\nPlease make sure input only contains letters.");
    }//GEN-LAST:event_NameFieldFocusLost

    private void PHFieldFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_PHFieldFocusLost
        String field = PHField.getText().trim();
        if (field.isEmpty()) return;
        GeneralMethods.InputValidation(PHField, null, 9, 9, "\\d+", "Invalid phone number entered.\nPlease make sure input only contains digits and is exactly 9 characters long excluding the country code (+60).");
    }//GEN-LAST:event_PHFieldFocusLost

    private void EmailFieldFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_EmailFieldFocusLost
        String field = EmailField.getText().trim();
        if (field.isEmpty()) return;
        GeneralMethods.InputValidation(EmailField, null, 1, Integer.MAX_VALUE, "^[\\w.-]+@[\\w.-]+\\.\\w+$", "Invalid email address entered.\nPlease make sure input does not contain any illegal characters and includes the email domain (Example: @gmail.com).");
    }//GEN-LAST:event_EmailFieldFocusLost

    private void AddressFieldFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_AddressFieldFocusLost
        String field = AddressField.getText().trim();
        if (field.isEmpty()) return;
        GeneralMethods.InputValidation(AddressField, null, 1, Integer.MAX_VALUE, "[a-zA-Z0-9 ]+", "Invalid address entered.\nPlease make sure input does not contain any illegal characters.");
    }//GEN-LAST:event_AddressFieldFocusLost

    private void SubjectFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SubjectFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_SubjectFieldActionPerformed

    private void LevelFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LevelFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_LevelFieldActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField AddressField;
    private javax.swing.JLabel AddressLabel;
    private javax.swing.JTextField EmailField;
    private javax.swing.JLabel EmailLabel;
    private javax.swing.JComboBox<String> GenderField;
    private javax.swing.JLabel GenderLabel;
    private javax.swing.JComboBox<String> LevelField;
    private javax.swing.JLabel LevelLabel;
    private javax.swing.JTextField NameField;
    private javax.swing.JLabel NameLabel;
    private javax.swing.JLabel NewTutorIDField;
    private AdminFrontend.ImagePanel NewTutorPFP;
    private javax.swing.JTextField PHField;
    private javax.swing.JLabel PHFormatLabel;
    private javax.swing.JLabel PHLabel;
    private javax.swing.JLabel PStudentInfoLabel2;
    private javax.swing.JLabel PersonalContactInfoLabel;
    private javax.swing.JButton RegisterButton;
    private javax.swing.JPanel RegisterTutorPage;
    private javax.swing.JPanel StudentIdNamePanel;
    private javax.swing.JLabel StudentManagementTitle;
    private javax.swing.JComboBox<String> SubjectField;
    private javax.swing.JLabel SubjectLabel;
    private javax.swing.JLabel TempPWField;
    private javax.swing.JLabel TempPWLabel;
    private javax.swing.JLabel TempUNField;
    private javax.swing.JLabel TempUNLabel;
    private javax.swing.JLabel TutorIDLabel;
    private javax.swing.JPanel TutorInfoLabel;
    private javax.swing.JButton TutorRegisterBackButton;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JSeparator jSeparator1;
    // End of variables declaration//GEN-END:variables
}
