/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package AdminFrontend;

import AdminBackend.GeneralMethods;
import AdminBackend.TutorMethods;
import AdminModels.Tutor;
import java.util.List;
import javax.swing.JOptionPane;

/**
 *
 * @author User
 */
public class ATutorProfileEditPanel extends javax.swing.JPanel {
    
    private final AdminFrame parent;
    Tutor selectedtutor;
    List<String> selectedlogin;
    
    /**
     * Creates new form ATutorProfileEditPanel
     */
    public ATutorProfileEditPanel(AdminFrame parent, Tutor selectedtutor, List<String> selectedlogin) {
        this.parent = parent;
        this.selectedtutor = selectedtutor;
        this.selectedlogin = selectedlogin;
        initComponents();
        GeneralMethods.LoadPFP(TutorPFP, "Profile Pictures/" + selectedtutor.getTutorid() + ".jpg");
        
        
        NameField.getDocument().addDocumentListener(GeneralMethods.MakeSimpleDocumentListener(() -> CheckForEmptyFields()));
        AddressField.getDocument().addDocumentListener(GeneralMethods.MakeSimpleDocumentListener(() -> CheckForEmptyFields()));
        PHField.getDocument().addDocumentListener(GeneralMethods.MakeSimpleDocumentListener(() -> CheckForEmptyFields()));
        EmailField.getDocument().addDocumentListener(GeneralMethods.MakeSimpleDocumentListener(() -> CheckForEmptyFields()));
        
        if (selectedtutor != null) {
            TutorIDField.setText(selectedtutor.getTutorid());
            TutorUsernameField.setText(selectedlogin.get(0));
            NameField.setText(selectedtutor.getTutorname());
            GenderField.setSelectedItem(GeneralMethods.Capitalize(selectedtutor.getTutorgender()));
            PHField.setText(selectedtutor.getTutorph().substring(3));
            EmailField.setText(selectedtutor.getTutoremail());
            AddressField.setText(selectedtutor.getTutoraddress());
            LevelField.setSelectedItem(GeneralMethods.Capitalize(selectedtutor.getTutorlevel()));
            SubjectField.setSelectedItem(GeneralMethods.Capitalize(selectedtutor.getTutorsubject()));
        }
    }
    
    private boolean ValidateAllInputs() {
        // Validate Name
        String name = NameField.getText().trim();
        if (name.isEmpty() || !name.matches("[a-zA-Z ]+")) {
            return false;
        }

        // Validate Phone Number
        String ph = PHField.getText().trim();
        if (ph.isEmpty() || ph.length() != 9 || !ph.matches("\\d+")) {
            return false;
        }

        // Validate Email
        String email = EmailField.getText().trim();
        if (email.isEmpty() || !email.matches("^[\\w.-]+@[\\w.-]+\\.\\w+$")) {
            return false;
        }

        // Validate Address
        String address = AddressField.getText().trim();
        if (address.isEmpty() || !address.matches("[a-zA-Z0-9 ]+")) {
            return false;
        }

        return true; // All validations passed
    }
    
    private void CheckForEmptyFields() {
        boolean valid =
        !NameField.getText().trim().isEmpty() &&
        !PHField.getText().trim().isEmpty() &&
        !EmailField.getText().trim().isEmpty() &&
        !AddressField.getText().trim().isEmpty();

        SaveButton.setEnabled(valid);
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        TutorProfileEditPanel = new javax.swing.JPanel();
        TutorProfileEditBackButton = new javax.swing.JButton();
        SaveButton = new javax.swing.JButton();
        TutorInfoPanel = new javax.swing.JPanel();
        TutorIDNamePanel = new javax.swing.JPanel();
        TutorIDLabel = new javax.swing.JLabel();
        TutorUsernameLabel = new javax.swing.JLabel();
        TutorIDField = new javax.swing.JLabel();
        TutorUsernameField = new javax.swing.JLabel();
        jSeparator2 = new javax.swing.JSeparator();
        TutorPFP = new AdminFrontend.ImagePanel();
        PersonalContactInfoLabel = new javax.swing.JLabel();
        NameLabel = new javax.swing.JLabel();
        GenderLabel = new javax.swing.JLabel();
        PHLabel = new javax.swing.JLabel();
        PHFormatLabel = new javax.swing.JLabel();
        EmailLabel = new javax.swing.JLabel();
        AddressLabel = new javax.swing.JLabel();
        NameField = new javax.swing.JTextField();
        GenderField = new javax.swing.JComboBox<>();
        PHField = new javax.swing.JTextField();
        EmailField = new javax.swing.JTextField();
        AddressField = new javax.swing.JTextField();
        TutorInfoLabel = new javax.swing.JLabel();
        LevelLabel = new javax.swing.JLabel();
        SubjectLabel = new javax.swing.JLabel();
        LevelField = new javax.swing.JComboBox<>();
        SubjectField = new javax.swing.JComboBox<>();
        jPanel2 = new javax.swing.JPanel();
        StudentManagementTitle = new javax.swing.JLabel();

        setMaximumSize(new java.awt.Dimension(930, 650));
        setMinimumSize(new java.awt.Dimension(930, 650));
        setPreferredSize(new java.awt.Dimension(930, 650));

        TutorProfileEditPanel.setMaximumSize(new java.awt.Dimension(930, 650));
        TutorProfileEditPanel.setMinimumSize(new java.awt.Dimension(930, 650));
        TutorProfileEditPanel.setPreferredSize(new java.awt.Dimension(930, 650));
        TutorProfileEditPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        TutorProfileEditBackButton.setText("Back");
        TutorProfileEditBackButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TutorProfileEditBackButtonActionPerformed(evt);
            }
        });
        TutorProfileEditPanel.add(TutorProfileEditBackButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(830, 565, 70, 35));

        SaveButton.setText("Save");
        SaveButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SaveButtonActionPerformed(evt);
            }
        });
        TutorProfileEditPanel.add(SaveButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(730, 565, 80, 35));

        TutorInfoPanel.setMaximumSize(new java.awt.Dimension(10, 10));
        TutorInfoPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        TutorIDNamePanel.setMaximumSize(new java.awt.Dimension(200, 80));
        TutorIDNamePanel.setMinimumSize(new java.awt.Dimension(200, 80));
        TutorIDNamePanel.setPreferredSize(new java.awt.Dimension(200, 80));
        TutorIDNamePanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        TutorIDLabel.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        TutorIDLabel.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        TutorIDLabel.setText("Tutor ID:");
        TutorIDLabel.setToolTipText("");
        TutorIDLabel.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);
        TutorIDNamePanel.add(TutorIDLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 25, 160, -1));

        TutorUsernameLabel.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        TutorUsernameLabel.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        TutorUsernameLabel.setText("Username:");
        TutorUsernameLabel.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);
        TutorIDNamePanel.add(TutorUsernameLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 55, 160, -1));

        TutorIDField.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        TutorIDField.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        TutorIDField.setText("Tutor ID");
        TutorIDField.setToolTipText("");
        TutorIDField.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);
        TutorIDNamePanel.add(TutorIDField, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 25, 110, -1));

        TutorUsernameField.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        TutorUsernameField.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        TutorUsernameField.setText("Username");
        TutorUsernameField.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);
        TutorIDNamePanel.add(TutorUsernameField, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 55, 110, -1));

        TutorInfoPanel.add(TutorIDNamePanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 6, 320, 100));
        TutorInfoPanel.add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 120, 830, 10));

        javax.swing.GroupLayout TutorPFPLayout = new javax.swing.GroupLayout(TutorPFP);
        TutorPFP.setLayout(TutorPFPLayout);
        TutorPFPLayout.setHorizontalGroup(
            TutorPFPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        TutorPFPLayout.setVerticalGroup(
            TutorPFPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        TutorInfoPanel.add(TutorPFP, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 6, 100, 100));

        PersonalContactInfoLabel.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        PersonalContactInfoLabel.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        PersonalContactInfoLabel.setText("Personal & Contact Information");
        PersonalContactInfoLabel.setToolTipText("");
        PersonalContactInfoLabel.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);
        TutorInfoPanel.add(PersonalContactInfoLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 140, -1, 40));

        NameLabel.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        NameLabel.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        NameLabel.setText("Name:");
        NameLabel.setToolTipText("");
        NameLabel.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);
        TutorInfoPanel.add(NameLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 190, -1, 30));

        GenderLabel.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        GenderLabel.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        GenderLabel.setText("Gender:");
        GenderLabel.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);
        TutorInfoPanel.add(GenderLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 230, -1, 30));

        PHLabel.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        PHLabel.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        PHLabel.setText("Phone Number:");
        PHLabel.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);
        TutorInfoPanel.add(PHLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 310, -1, 30));

        PHFormatLabel.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        PHFormatLabel.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        PHFormatLabel.setText("+60 ");
        PHFormatLabel.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);
        TutorInfoPanel.add(PHFormatLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 310, 30, 30));

        EmailLabel.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        EmailLabel.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        EmailLabel.setText("Email Address:");
        EmailLabel.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);
        TutorInfoPanel.add(EmailLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 350, -1, 30));

        AddressLabel.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        AddressLabel.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        AddressLabel.setText("Address:");
        AddressLabel.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);
        TutorInfoPanel.add(AddressLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 270, -1, 30));

        NameField.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                NameFieldFocusLost(evt);
            }
        });
        NameField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NameFieldActionPerformed(evt);
            }
        });
        TutorInfoPanel.add(NameField, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 190, 330, 30));

        GenderField.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Male", "Female" }));
        GenderField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                GenderFieldActionPerformed(evt);
            }
        });
        TutorInfoPanel.add(GenderField, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 230, 100, 30));

        PHField.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                PHFieldFocusLost(evt);
            }
        });
        TutorInfoPanel.add(PHField, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 310, 300, 30));

        EmailField.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                EmailFieldFocusLost(evt);
            }
        });
        EmailField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EmailFieldActionPerformed(evt);
            }
        });
        TutorInfoPanel.add(EmailField, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 350, 330, 30));

        AddressField.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                AddressFieldFocusLost(evt);
            }
        });
        TutorInfoPanel.add(AddressField, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 270, 330, 30));

        TutorInfoLabel.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        TutorInfoLabel.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        TutorInfoLabel.setText("Tutor Information");
        TutorInfoLabel.setToolTipText("");
        TutorInfoLabel.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);
        TutorInfoPanel.add(TutorInfoLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 140, -1, 40));

        LevelLabel.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        LevelLabel.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        LevelLabel.setText("Level: ");
        LevelLabel.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);
        TutorInfoPanel.add(LevelLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 190, -1, 30));

        SubjectLabel.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        SubjectLabel.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        SubjectLabel.setText("Subject:");
        SubjectLabel.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);
        TutorInfoPanel.add(SubjectLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 240, -1, 30));

        LevelField.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Form 1", "Form 2", "Form 3", "Form 4", "Form 5" }));
        LevelField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LevelFieldActionPerformed(evt);
            }
        });
        TutorInfoPanel.add(LevelField, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 190, 150, 30));

        SubjectField.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "English", "Mathematics", "Science" }));
        SubjectField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SubjectFieldActionPerformed(evt);
            }
        });
        TutorInfoPanel.add(SubjectField, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 240, 150, 30));

        TutorProfileEditPanel.add(TutorInfoPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 110, 830, 460));

        jPanel2.setBackground(new java.awt.Color(184, 186, 191));
        jPanel2.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        StudentManagementTitle.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        StudentManagementTitle.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        StudentManagementTitle.setText("Edit Tutor Profile");
        StudentManagementTitle.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(StudentManagementTitle, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 926, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addComponent(StudentManagementTitle)
                .addContainerGap(33, Short.MAX_VALUE))
        );

        TutorProfileEditPanel.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 930, 100));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(TutorProfileEditPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(TutorProfileEditPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void TutorProfileEditBackButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TutorProfileEditBackButtonActionPerformed
        parent.switchPanelParameters("tprofile", selectedtutor, selectedlogin);
    }//GEN-LAST:event_TutorProfileEditBackButtonActionPerformed

    private void SaveButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SaveButtonActionPerformed
        if (!ValidateAllInputs()) return;
        
        String newtutorid = TutorIDField.getText();
        String newtutorlevel = (String) LevelField.getSelectedItem();
        String newtutorname = GeneralMethods.Capitalize(NameField.getText());
        String newtutorgender = (String) GenderField.getSelectedItem();
        String newtutoraddress = GeneralMethods.Capitalize(AddressField.getText());
        String newtutorsubject = (String) SubjectField.getSelectedItem();
        String newtutorph = "+60" + PHField.getText();
        String newtutoremail = EmailField.getText();

        if (TutorMethods.ValidateTutor(newtutorid, newtutorname, newtutorph, newtutoremail)) {
            Tutor newtutor = new Tutor(newtutorid, newtutorlevel, newtutorname, newtutorgender, newtutoraddress, newtutorsubject, newtutorph, newtutoremail);

            TutorMethods.SaveNewTutor(newtutor);
            JOptionPane.showMessageDialog(null, "Changes saved successfully!");
            parent.switchPanelParameters("tprofile", newtutor, GeneralMethods.GetLoginCreds(newtutorid));
        }
        
    }//GEN-LAST:event_SaveButtonActionPerformed

    private void NameFieldFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_NameFieldFocusLost
        String field = NameField.getText().trim();
        if (field.isEmpty()) return;
        GeneralMethods.InputValidation(NameField, null, 1, Integer.MAX_VALUE, "[a-zA-Z ]+", "Invalid name entered.\nPlease make sure input only contains letters.");
    }//GEN-LAST:event_NameFieldFocusLost

    private void NameFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NameFieldActionPerformed

    }//GEN-LAST:event_NameFieldActionPerformed

    private void GenderFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_GenderFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_GenderFieldActionPerformed

    private void PHFieldFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_PHFieldFocusLost
        String field = PHField.getText().trim();
        if (field.isEmpty()) return;
        GeneralMethods.InputValidation(PHField, null, 9, 9, "\\d+", "Invalid phone number entered.\nPlease make sure input only contains digits and is exactly 9 characters long excluding the country code (+60).");
    }//GEN-LAST:event_PHFieldFocusLost

    private void EmailFieldFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_EmailFieldFocusLost
        String field = EmailField.getText().trim();
        if (field.isEmpty()) return;
        GeneralMethods.InputValidation(EmailField, null, 1, Integer.MAX_VALUE, "^[\\w.-]+@[\\w.-]+\\.\\w+$", "Invalid email address entered.\nPlease make sure input does not contain any illegal characters and includes the email domain (Example: @gmail.com).");
    }//GEN-LAST:event_EmailFieldFocusLost

    private void EmailFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EmailFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_EmailFieldActionPerformed

    private void AddressFieldFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_AddressFieldFocusLost
        String field = AddressField.getText().trim();
        if (field.isEmpty()) return;
        GeneralMethods.InputValidation(AddressField, null, 1, Integer.MAX_VALUE, "[a-zA-Z0-9 ]+", "Invalid address entered.\nPlease make sure input does not contain any illegal characters.");
    }//GEN-LAST:event_AddressFieldFocusLost

    private void LevelFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LevelFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_LevelFieldActionPerformed

    private void SubjectFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SubjectFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_SubjectFieldActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField AddressField;
    private javax.swing.JLabel AddressLabel;
    private javax.swing.JTextField EmailField;
    private javax.swing.JLabel EmailLabel;
    private javax.swing.JComboBox<String> GenderField;
    private javax.swing.JLabel GenderLabel;
    private javax.swing.JComboBox<String> LevelField;
    private javax.swing.JLabel LevelLabel;
    private javax.swing.JTextField NameField;
    private javax.swing.JLabel NameLabel;
    private javax.swing.JTextField PHField;
    private javax.swing.JLabel PHFormatLabel;
    private javax.swing.JLabel PHLabel;
    private javax.swing.JLabel PersonalContactInfoLabel;
    private javax.swing.JButton SaveButton;
    private javax.swing.JLabel StudentManagementTitle;
    private javax.swing.JComboBox<String> SubjectField;
    private javax.swing.JLabel SubjectLabel;
    private javax.swing.JLabel TutorIDField;
    private javax.swing.JLabel TutorIDLabel;
    private javax.swing.JPanel TutorIDNamePanel;
    private javax.swing.JLabel TutorInfoLabel;
    private javax.swing.JPanel TutorInfoPanel;
    private AdminFrontend.ImagePanel TutorPFP;
    private javax.swing.JButton TutorProfileEditBackButton;
    private javax.swing.JPanel TutorProfileEditPanel;
    private javax.swing.JLabel TutorUsernameField;
    private javax.swing.JLabel TutorUsernameLabel;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JSeparator jSeparator2;
    // End of variables declaration//GEN-END:variables
}
