/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package AdminFrontend;

import AdminBackend.GeneralMethods;
import AdminBackend.TutorMethods;
import AdminModels.Tutor;
import java.util.List;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author User
 */
public class ATutorMenuPanel extends javax.swing.JPanel {

    private final AdminFrame parent;
    DefaultTableModel tutortablemodel;
    
    /**
     * Creates new form ATutorMenuPanel
     */
    
    public ATutorMenuPanel(AdminFrame parent) {
        this.parent = parent;
        initComponents();
        this.tutortablemodel = (DefaultTableModel) TutorList.getModel();
        TutorMethods.PopulateTutorList(tutortablemodel);
    }

    public JTable getTutorList() {
        return TutorList;
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        StudentMenuPage = new javax.swing.JPanel();
        TutorScrollPanel = new javax.swing.JScrollPane();
        TutorList = new javax.swing.JTable();
        RegisterTutorButton = new javax.swing.JButton();
        TutorMenuBackButton = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        StudentManagementTitle = new javax.swing.JLabel();

        StudentMenuPage.setMaximumSize(new java.awt.Dimension(930, 650));
        StudentMenuPage.setMinimumSize(new java.awt.Dimension(930, 650));
        StudentMenuPage.setPreferredSize(new java.awt.Dimension(930, 650));
        StudentMenuPage.setRequestFocusEnabled(false);
        StudentMenuPage.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        TutorList.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        TutorList.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Tutor ID", "Tutor Name", "Level", "Subject"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        TutorList.setMaximumSize(null);
        TutorList.setMinimumSize(null);
        TutorList.setRowHeight(30);
        TutorList.setRowMargin(5);
        TutorList.getTableHeader().setResizingAllowed(false);
        TutorList.getTableHeader().setReorderingAllowed(false);
        TutorList.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                TutorListMouseClicked(evt);
            }
        });
        TutorList.addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentShown(java.awt.event.ComponentEvent evt) {
                TutorListComponentShown(evt);
            }
        });
        TutorScrollPanel.setViewportView(TutorList);
        if (TutorList.getColumnModel().getColumnCount() > 0) {
            TutorList.getColumnModel().getColumn(0).setPreferredWidth(10);
            TutorList.getColumnModel().getColumn(1).setPreferredWidth(300);
            TutorList.getColumnModel().getColumn(2).setPreferredWidth(50);
            TutorList.getColumnModel().getColumn(3).setPreferredWidth(50);
        }

        StudentMenuPage.add(TutorScrollPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 140, 870, 390));

        RegisterTutorButton.setText("Register New Tutor");
        RegisterTutorButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RegisterTutorButtonActionPerformed(evt);
            }
        });
        StudentMenuPage.add(RegisterTutorButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 565, 170, 35));

        TutorMenuBackButton.setText("Back");
        TutorMenuBackButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TutorMenuBackButtonActionPerformed(evt);
            }
        });
        StudentMenuPage.add(TutorMenuBackButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(830, 565, 70, 35));

        jPanel2.setBackground(new java.awt.Color(184, 186, 191));
        jPanel2.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        StudentManagementTitle.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        StudentManagementTitle.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        StudentManagementTitle.setText("Tutor Management");
        StudentManagementTitle.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(StudentManagementTitle, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 926, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addComponent(StudentManagementTitle)
                .addContainerGap(33, Short.MAX_VALUE))
        );

        StudentMenuPage.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 930, 100));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 930, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(StudentMenuPage, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 650, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(StudentMenuPage, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void RegisterTutorButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RegisterTutorButtonActionPerformed
        parent.switchPanel("tregister");
    }//GEN-LAST:event_RegisterTutorButtonActionPerformed

    private void TutorMenuBackButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TutorMenuBackButtonActionPerformed
        parent.switchPanel("admin");
    }//GEN-LAST:event_TutorMenuBackButtonActionPerformed

    private void TutorListMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TutorListMouseClicked
        String selectedtid = tutortablemodel.getValueAt(TutorList.getSelectedRow(), 0).toString();
        Tutor selectedtutor = TutorMethods.GetTutorByID(selectedtid);
        List<String> creds = GeneralMethods.GetLoginCreds(selectedtid);
        
        parent.switchPanelParameters("tprofile", selectedtutor, creds);
    }//GEN-LAST:event_TutorListMouseClicked

    private void TutorListComponentShown(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_TutorListComponentShown
        DefaultTableModel model = parent.getTutorTableModel();
        TutorMethods.PopulateTutorList(model);
    }//GEN-LAST:event_TutorListComponentShown

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton RegisterTutorButton;
    private javax.swing.JLabel StudentManagementTitle;
    private javax.swing.JPanel StudentMenuPage;
    private javax.swing.JTable TutorList;
    private javax.swing.JButton TutorMenuBackButton;
    private javax.swing.JScrollPane TutorScrollPanel;
    private javax.swing.JPanel jPanel2;
    // End of variables declaration//GEN-END:variables
}
