/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package AdminFrontend;

import AdminBackend.GeneralMethods;
import AdminBackend.TutorMethods;
import AdminModels.Tutor;
import java.io.IOException;
import java.util.List;
import javax.swing.JButton;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author User
 */
public class ATutorProfilePanel extends javax.swing.JPanel {
    
    private final AdminFrame parent;
    Tutor saveselectedtutor;
    List<String> saveselectedlogin;
    PopupLoginCredentials changeloginpopup;
    DefaultTableModel subjecttablemodel;

    /**
     * Creates new form AdminProfile
     */
    public ATutorProfilePanel(AdminFrame parent, Tutor selectedtutor, List<String> selectedlogin) throws IOException {
        this.parent = parent;
        this.saveselectedtutor = selectedtutor;
        this.saveselectedlogin = selectedlogin;
        initComponents();
        
        if (selectedtutor != null) {
            TutorIDField.setText(selectedtutor.getTutorid());
            TutorNameField.setText(selectedtutor.getTutorname());
            TutorUsernameField.setText(saveselectedlogin.get(0));
            TutorGenderField.setText(selectedtutor.getTutorgender());
            TutorPHField.setText(selectedtutor.getTutorph());
            TutorEmailField.setText(selectedtutor.getTutoremail());
            TutorAddressField.setText(selectedtutor.getTutoraddress());
            TutorLevelField.setText(selectedtutor.getTutorlevel());
            TutorSubjectField.setText(selectedtutor.getTutorsubject());
            GeneralMethods.LoadPFP(TutorProfilePFP, "Profile Pictures/"+ selectedtutor.getTutorid() +".jpg");
        }
        
        changeloginpopup = new PopupLoginCredentials(saveselectedlogin);
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        AdminProfilePage = new javax.swing.JPanel();
        TutorInfoTab = new javax.swing.JPanel();
        jSeparator1 = new javax.swing.JSeparator();
        DeleteTutorButton = new javax.swing.JButton();
        EditTutorInfoButton = new javax.swing.JButton();
        ChangeTutorLoginButton = new javax.swing.JButton();
        TutorProfileBackButton = new javax.swing.JButton();
        ResetPFPButton = new javax.swing.JButton();
        LeftPanel = new javax.swing.JPanel();
        TutorIDNamePanel = new javax.swing.JPanel();
        TutorIDLabel = new javax.swing.JLabel();
        TutorNameLabel = new javax.swing.JLabel();
        TutorUsernameLabel = new javax.swing.JLabel();
        TutorIDField = new javax.swing.JLabel();
        TutorNameField = new javax.swing.JLabel();
        TutorUsernameField = new javax.swing.JLabel();
        TutorProfilePFP = new AdminFrontend.ImagePanel();
        RightPanel = new javax.swing.JPanel();
        TutorInfoPanel = new javax.swing.JPanel();
        PersonalInformationLabel = new javax.swing.JLabel();
        TutorGenderLabel = new javax.swing.JLabel();
        TutorGenderField = new javax.swing.JLabel();
        TutorPHLabel = new javax.swing.JLabel();
        TutorPHField = new javax.swing.JLabel();
        TutorEmailLabel = new javax.swing.JLabel();
        TutorEmailField = new javax.swing.JLabel();
        TutorAddressLabel = new javax.swing.JLabel();
        TutorAddressField = new javax.swing.JLabel();
        TutorLevelLabel = new javax.swing.JLabel();
        TutorLevelField = new javax.swing.JLabel();
        TutorSubjectLabel = new javax.swing.JLabel();
        TutorSubjectField = new javax.swing.JLabel();
        ContactInformationLabel = new javax.swing.JLabel();
        TutorInformationLabel = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        StudentManagementTitle = new javax.swing.JLabel();

        AdminProfilePage.setMaximumSize(new java.awt.Dimension(930, 650));
        AdminProfilePage.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        TutorInfoTab.setMaximumSize(new java.awt.Dimension(850, 500));
        TutorInfoTab.setMinimumSize(new java.awt.Dimension(850, 500));
        TutorInfoTab.setPreferredSize(new java.awt.Dimension(850, 500));
        TutorInfoTab.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jSeparator1.setOrientation(javax.swing.SwingConstants.VERTICAL);
        TutorInfoTab.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 20, 10, 460));

        DeleteTutorButton.setText("Delete");
        DeleteTutorButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DeleteTutorButtonActionPerformed(evt);
            }
        });
        TutorInfoTab.add(DeleteTutorButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 445, 90, 35));

        EditTutorInfoButton.setText("Edit Tutor Information");
        EditTutorInfoButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EditTutorInfoButtonActionPerformed(evt);
            }
        });
        TutorInfoTab.add(EditTutorInfoButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 445, 170, 35));

        ChangeTutorLoginButton.setText("Change Tutor Login Credentials");
        ChangeTutorLoginButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ChangeTutorLoginButtonActionPerformed(evt);
            }
        });
        TutorInfoTab.add(ChangeTutorLoginButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 445, 230, 35));

        TutorProfileBackButton.setText("Back");
        TutorProfileBackButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TutorProfileBackButtonActionPerformed(evt);
            }
        });
        TutorInfoTab.add(TutorProfileBackButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(830, 445, 70, 35));

        ResetPFPButton.setText("Reset Profile Picture");
        ResetPFPButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ResetPFPButtonActionPerformed(evt);
            }
        });
        TutorInfoTab.add(ResetPFPButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 445, 200, 35));

        LeftPanel.setMaximumSize(new java.awt.Dimension(300, 500));
        LeftPanel.setMinimumSize(new java.awt.Dimension(300, 500));
        LeftPanel.setPreferredSize(new java.awt.Dimension(300, 500));
        LeftPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        TutorIDNamePanel.setMaximumSize(new java.awt.Dimension(200, 80));
        TutorIDNamePanel.setMinimumSize(new java.awt.Dimension(200, 80));
        TutorIDNamePanel.setPreferredSize(new java.awt.Dimension(200, 80));
        TutorIDNamePanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        TutorIDLabel.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        TutorIDLabel.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        TutorIDLabel.setText("Tutor ID:");
        TutorIDLabel.setToolTipText("");
        TutorIDLabel.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);
        TutorIDNamePanel.add(TutorIDLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 80, -1));

        TutorNameLabel.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        TutorNameLabel.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        TutorNameLabel.setText("Name:");
        TutorNameLabel.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);
        TutorIDNamePanel.add(TutorNameLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 30, 80, -1));

        TutorUsernameLabel.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        TutorUsernameLabel.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        TutorUsernameLabel.setText("Username:");
        TutorUsernameLabel.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);
        TutorIDNamePanel.add(TutorUsernameLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 60, 80, -1));

        TutorIDField.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        TutorIDField.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        TutorIDField.setText("Tutor ID");
        TutorIDField.setToolTipText("");
        TutorIDField.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);
        TutorIDNamePanel.add(TutorIDField, new org.netbeans.lib.awtextra.AbsoluteConstraints(85, 0, 115, 20));

        TutorNameField.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        TutorNameField.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        TutorNameField.setText("Tutor Name");
        TutorNameField.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);
        TutorIDNamePanel.add(TutorNameField, new org.netbeans.lib.awtextra.AbsoluteConstraints(85, 30, 115, 20));

        TutorUsernameField.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        TutorUsernameField.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        TutorUsernameField.setText("Username");
        TutorUsernameField.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);
        TutorIDNamePanel.add(TutorUsernameField, new org.netbeans.lib.awtextra.AbsoluteConstraints(85, 60, 115, 20));

        LeftPanel.add(TutorIDNamePanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 230, 200, 130));

        TutorProfilePFP.setMaximumSize(new java.awt.Dimension(200, 200));
        TutorProfilePFP.setMinimumSize(new java.awt.Dimension(200, 200));

        javax.swing.GroupLayout TutorProfilePFPLayout = new javax.swing.GroupLayout(TutorProfilePFP);
        TutorProfilePFP.setLayout(TutorProfilePFPLayout);
        TutorProfilePFPLayout.setHorizontalGroup(
            TutorProfilePFPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 200, Short.MAX_VALUE)
        );
        TutorProfilePFPLayout.setVerticalGroup(
            TutorProfilePFPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 200, Short.MAX_VALUE)
        );

        LeftPanel.add(TutorProfilePFP, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 200, 200));

        TutorInfoTab.add(LeftPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 20, 200, 370));

        RightPanel.setMaximumSize(new java.awt.Dimension(630, 500));
        RightPanel.setMinimumSize(new java.awt.Dimension(630, 500));

        TutorInfoPanel.setMaximumSize(new java.awt.Dimension(10, 10));
        TutorInfoPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        PersonalInformationLabel.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        PersonalInformationLabel.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        PersonalInformationLabel.setText("Personal Information");
        PersonalInformationLabel.setToolTipText("");
        PersonalInformationLabel.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);
        TutorInfoPanel.add(PersonalInformationLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        TutorGenderLabel.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        TutorGenderLabel.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        TutorGenderLabel.setText("Gender");
        TutorGenderLabel.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);
        TutorInfoPanel.add(TutorGenderLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 40, -1, -1));

        TutorGenderField.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        TutorGenderField.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        TutorGenderField.setText("-");
        TutorGenderField.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);
        TutorInfoPanel.add(TutorGenderField, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 40, -1, -1));

        TutorPHLabel.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        TutorPHLabel.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        TutorPHLabel.setText("Phone Number:");
        TutorPHLabel.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);
        TutorInfoPanel.add(TutorPHLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 180, -1, 20));

        TutorPHField.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        TutorPHField.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        TutorPHField.setText("-");
        TutorPHField.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);
        TutorInfoPanel.add(TutorPHField, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 180, -1, 20));

        TutorEmailLabel.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        TutorEmailLabel.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        TutorEmailLabel.setText("Email Address:");
        TutorEmailLabel.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);
        TutorInfoPanel.add(TutorEmailLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 210, -1, 20));

        TutorEmailField.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        TutorEmailField.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        TutorEmailField.setText("-");
        TutorEmailField.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);
        TutorInfoPanel.add(TutorEmailField, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 210, -1, 20));

        TutorAddressLabel.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        TutorAddressLabel.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        TutorAddressLabel.setText("Address:");
        TutorAddressLabel.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);
        TutorInfoPanel.add(TutorAddressLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 70, -1, 20));

        TutorAddressField.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        TutorAddressField.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        TutorAddressField.setText("-");
        TutorAddressField.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);
        TutorInfoPanel.add(TutorAddressField, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 70, -1, 20));

        TutorLevelLabel.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        TutorLevelLabel.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        TutorLevelLabel.setText("Level:");
        TutorLevelLabel.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);
        TutorInfoPanel.add(TutorLevelLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 320, -1, 20));

        TutorLevelField.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        TutorLevelField.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        TutorLevelField.setText("-");
        TutorLevelField.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);
        TutorInfoPanel.add(TutorLevelField, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 320, -1, 20));

        TutorSubjectLabel.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        TutorSubjectLabel.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        TutorSubjectLabel.setText("Subject:");
        TutorSubjectLabel.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);
        TutorInfoPanel.add(TutorSubjectLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 350, -1, 20));

        TutorSubjectField.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        TutorSubjectField.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        TutorSubjectField.setText("-");
        TutorSubjectField.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);
        TutorInfoPanel.add(TutorSubjectField, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 350, -1, 20));

        ContactInformationLabel.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        ContactInformationLabel.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        ContactInformationLabel.setText("Contact Information");
        ContactInformationLabel.setToolTipText("");
        ContactInformationLabel.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);
        TutorInfoPanel.add(ContactInformationLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 140, -1, -1));

        TutorInformationLabel.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        TutorInformationLabel.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        TutorInformationLabel.setText("Tutor Information");
        TutorInformationLabel.setToolTipText("");
        TutorInformationLabel.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);
        TutorInfoPanel.add(TutorInformationLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 280, -1, -1));

        javax.swing.GroupLayout RightPanelLayout = new javax.swing.GroupLayout(RightPanel);
        RightPanel.setLayout(RightPanelLayout);
        RightPanelLayout.setHorizontalGroup(
            RightPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, RightPanelLayout.createSequentialGroup()
                .addContainerGap(26, Short.MAX_VALUE)
                .addComponent(TutorInfoPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 608, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        RightPanelLayout.setVerticalGroup(
            RightPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(RightPanelLayout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(TutorInfoPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(111, Short.MAX_VALUE))
        );

        TutorInfoTab.add(RightPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(257, 0, 640, 420));

        AdminProfilePage.add(TutorInfoTab, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 120, 930, 530));

        jPanel2.setBackground(new java.awt.Color(184, 186, 191));
        jPanel2.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        StudentManagementTitle.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        StudentManagementTitle.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        StudentManagementTitle.setText("Tutor Profile");
        StudentManagementTitle.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(StudentManagementTitle, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 926, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addComponent(StudentManagementTitle)
                .addContainerGap(33, Short.MAX_VALUE))
        );

        AdminProfilePage.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 930, 100));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 930, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(AdminProfilePage, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 650, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(AdminProfilePage, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void EditTutorInfoButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EditTutorInfoButtonActionPerformed
        parent.switchPanelParameters("tprofileedit", saveselectedtutor, saveselectedlogin);
    }//GEN-LAST:event_EditTutorInfoButtonActionPerformed

    private void TutorProfileBackButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TutorProfileBackButtonActionPerformed
        parent.switchPanel("tutor");
    }//GEN-LAST:event_TutorProfileBackButtonActionPerformed

    private void ResetPFPButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ResetPFPButtonActionPerformed
        GeneralMethods.ResetPFP(this, saveselectedtutor.getTutorid());
        GeneralMethods.LoadPFP(TutorProfilePFP, "Profile Pictures/"+ saveselectedtutor.getTutorid() +".jpg");
    }//GEN-LAST:event_ResetPFPButtonActionPerformed

    private void ChangeTutorLoginButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ChangeTutorLoginButtonActionPerformed
        PopupLoginCredentials popup = new PopupLoginCredentials(saveselectedlogin);
        JButton[] options = {popup.getLCOKButton(), popup.getLCCancelButton()};
        JButton okbutton = options[0];
        
        while (true) {
            JOptionPane.showOptionDialog(this, popup, "Change Login Credentials", JOptionPane.DEFAULT_OPTION, JOptionPane.PLAIN_MESSAGE, null, options, okbutton);
            
            if (popup.getLCChoice() == 0) {
                if (GeneralMethods.ValidateUsername(saveselectedlogin.get(0).trim(), popup.getNewUsername().trim())) {
                    int choice2 = JOptionPane.showConfirmDialog(this, "Confirm changes to tutor login credentials?", "Login Credentials Change Confirmation", JOptionPane.YES_NO_OPTION);
                    if (choice2 == JOptionPane.OK_OPTION) {
                        String newusername = popup.getNewUsername();
                        String newpassword = popup.getNewPassword();
                        GeneralMethods.SaveNewLogin(saveselectedtutor.getTutorid(), newusername, newpassword);
                        TutorUsernameField.setText(newusername);
                        popup.setUsername(newusername);
                        saveselectedlogin.set(0, newusername);
                        saveselectedlogin.set(1, newpassword);
                        popup.setPassword(newpassword);
                        revalidate();
                        repaint();
                        break;
                    }
                } else {
                    popup.getUsernameField().setText(saveselectedlogin.get(0));
                }
            } else {
                break;
            }
        }
        
        
    }//GEN-LAST:event_ChangeTutorLoginButtonActionPerformed

    private void DeleteTutorButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DeleteTutorButtonActionPerformed
        String selectedtid = saveselectedtutor.getTutorid();
        int choice = JOptionPane.showConfirmDialog(this, "Delete tutor " + saveselectedtutor.getTutorname() + " (" + selectedtid + ")?", "Deletion Confirmation", JOptionPane.YES_NO_OPTION);
        if (choice == JOptionPane.YES_OPTION) {
            TutorMethods.DeleteTutor(selectedtid);
            JOptionPane.showMessageDialog(null, "Tutor successfully deleted.");
            parent.switchPanel("tutor");
        } else {
            return;
        }
    }//GEN-LAST:event_DeleteTutorButtonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel AdminProfilePage;
    private javax.swing.JButton ChangeTutorLoginButton;
    private javax.swing.JLabel ContactInformationLabel;
    private javax.swing.JButton DeleteTutorButton;
    private javax.swing.JButton EditTutorInfoButton;
    private javax.swing.JPanel LeftPanel;
    private javax.swing.JLabel PersonalInformationLabel;
    private javax.swing.JButton ResetPFPButton;
    private javax.swing.JPanel RightPanel;
    private javax.swing.JLabel StudentManagementTitle;
    private javax.swing.JLabel TutorAddressField;
    private javax.swing.JLabel TutorAddressLabel;
    private javax.swing.JLabel TutorEmailField;
    private javax.swing.JLabel TutorEmailLabel;
    private javax.swing.JLabel TutorGenderField;
    private javax.swing.JLabel TutorGenderLabel;
    private javax.swing.JLabel TutorIDField;
    private javax.swing.JLabel TutorIDLabel;
    private javax.swing.JPanel TutorIDNamePanel;
    private javax.swing.JPanel TutorInfoPanel;
    private javax.swing.JPanel TutorInfoTab;
    private javax.swing.JLabel TutorInformationLabel;
    private javax.swing.JLabel TutorLevelField;
    private javax.swing.JLabel TutorLevelLabel;
    private javax.swing.JLabel TutorNameField;
    private javax.swing.JLabel TutorNameLabel;
    private javax.swing.JLabel TutorPHField;
    private javax.swing.JLabel TutorPHLabel;
    private javax.swing.JButton TutorProfileBackButton;
    private AdminFrontend.ImagePanel TutorProfilePFP;
    private javax.swing.JLabel TutorSubjectField;
    private javax.swing.JLabel TutorSubjectLabel;
    private javax.swing.JLabel TutorUsernameField;
    private javax.swing.JLabel TutorUsernameLabel;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JSeparator jSeparator1;
    // End of variables declaration//GEN-END:variables
}
