/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package AdminFrontend;

import java.awt.Graphics;
import java.awt.Graphics2D;
import java.awt.Shape;
import java.awt.geom.Ellipse2D;
import java.awt.image.BufferedImage;

/**
 *
 * @author User
 */
public class ImagePanel extends javax.swing.JPanel {
private BufferedImage image;
    /**
     * Creates new form ImagePanel
     */
    public ImagePanel() {
        initComponents();
        setOpaque(false);
    }
    
        public void setImage(BufferedImage img) {
        this.image = img;
        repaint();
    }

    @Override
    protected void paintComponent(Graphics g) {
        int size = Math.min(getWidth(), getHeight());
        Graphics2D g2 = (Graphics2D) g.create();
        Shape circle = new Ellipse2D.Float(0, 0, size, size);
        g2.setClip(circle);
        
        if (image != null) {
            int pw = getWidth(), ph = getHeight();
            int iw = image.getWidth(), ih = image.getHeight();
            // use max to *cover* the panel
            double scale = Math.max((double)pw/iw, (double)ph/ih);
            int w = (int)(iw * scale), h = (int)(ih * scale);
            int x = (pw - w) / 2;
            int y = (ph - h) / 2;
            g2.drawImage(image, x, y, w, h, this);
        }
  
        g2.dispose();
        super.paintComponent(g);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 200, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 200, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
