/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package AdminFrontend;

import AdminBackend.AdminMethods;
import AdminBackend.GeneralMethods;
import AdminBackend.PaymentMethods;
import AdminBackend.ReceiptMethod;
import AdminModels.Payment;
import AdminModels.PaymentMade;
import java.awt.event.ItemEvent;
import java.awt.event.ItemListener;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;
import javax.swing.JButton;
import javax.swing.JOptionPane;
import javax.swing.ListSelectionModel;
import javax.swing.event.ListSelectionEvent;
import javax.swing.event.ListSelectionListener;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author User
 */
public class PaymentPanel extends javax.swing.JPanel {
    
    private final AdminFrame parent;
    DefaultTableModel pendingpaymentsmodel;
    DefaultTableModel paymenthistorymodel;
    DefaultTableModel incomereportmodel;
    
     public PaymentPanel(AdminFrame parent) {
        this.parent = parent;
        initComponents();
        
        // Start a new thread for background work to prevent GUI freezing
        new Thread(() -> {
            PaymentMethods.GeneratePayment();
        }).start();
        
        NoRecordsLabel.setVisible(false);
        NoRecordsLabel1.setVisible(false);

        OutstandingAmount.setText(Float.toString(PaymentMethods.CalculateTotalPending()));
        
        // Get models for JTables in Payment Panel and populate them
        this.paymenthistorymodel = (DefaultTableModel) PaymentHistory.getModel();
        PaymentMethods.PopulatePaymentHistory(paymenthistorymodel, HistoryYearField.getSelectedItem().toString(), HistoryMonthField.getSelectedItem().toString());
                
        this.pendingpaymentsmodel = (DefaultTableModel) PendingPayments.getModel();
        PaymentMethods.PopulatePendingPayments(pendingpaymentsmodel, PendingYearField.getSelectedItem().toString(), PendingMonthField.getSelectedItem().toString());

        this.incomereportmodel = (DefaultTableModel) IncomeReport.getModel();
        PaymentMethods.PopulateIncomeReport(incomereportmodel, TotalAmount, YearField.getSelectedItem().toString(), MonthField.getSelectedItem().toString(), LevelField.getSelectedItem().toString(), SubjectField.getSelectedItem().toString());
        
        // Cumulative item listener for all Income Report filters
        ItemListener listener = new ItemListener() {
            @Override
            public void itemStateChanged(ItemEvent e) {
                if (e.getStateChange() == ItemEvent.SELECTED) {
                    PaymentMethods.PopulateIncomeReport(incomereportmodel, TotalAmount, YearField.getSelectedItem().toString(), MonthField.getSelectedItem().toString(), LevelField.getSelectedItem().toString(), SubjectField.getSelectedItem().toString());
                }
                
            }
        };

        YearField.addItemListener(listener);
        MonthField.addItemListener(listener);
        SubjectField.addItemListener(listener);
        LevelField.addItemListener(listener);
        
        // Selection listener for Payment History JTable (for receipt generation function)
        GenerateReceiptButton.setEnabled(false);
        
        ListSelectionModel selectionmodel = PaymentHistory.getSelectionModel();
        selectionmodel.setSelectionMode(ListSelectionModel.SINGLE_SELECTION);

        selectionmodel.addListSelectionListener(new ListSelectionListener() {
            @Override
            public void valueChanged(ListSelectionEvent event) {
                // Ignore adjusting events
                if (event.getValueIsAdjusting()) {
                    return;
                }

                int selectedRow = PaymentHistory.getSelectedRow();

                if (selectedRow >= 0) {
                    GenerateReceiptButton.setEnabled(true);
                } else {
                    GenerateReceiptButton.setEnabled(false);
                }
            }
        });
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        PaymentPage = new javax.swing.JPanel();
        PaymentTabbedPane = new javax.swing.JTabbedPane();
        PaymentHistoryTab = new javax.swing.JPanel();
        NoRecordsLabel = new javax.swing.JLabel();
        GenerateReceiptButton = new javax.swing.JButton();
        AcceptPaymentButton = new javax.swing.JButton();
        PaymentBackButton = new javax.swing.JButton();
        PaymentHistoryScrollPane = new javax.swing.JScrollPane();
        PaymentHistory = new javax.swing.JTable();
        HistoryYearField = new javax.swing.JComboBox<>();
        HistoryMonthField = new javax.swing.JComboBox<>();
        PendingPaymentsTab = new javax.swing.JPanel();
        NoRecordsLabel1 = new javax.swing.JLabel();
        PendingPaymentsScrollPane = new javax.swing.JScrollPane();
        PendingPayments = new javax.swing.JTable();
        OutstandingLabel = new javax.swing.JLabel();
        OutstandingAmount = new javax.swing.JLabel();
        PaymentBackButton2 = new javax.swing.JButton();
        PendingYearField = new javax.swing.JComboBox<>();
        PendingMonthField = new javax.swing.JComboBox<>();
        IncomeReportTab = new javax.swing.JPanel();
        YearLabel = new javax.swing.JLabel();
        MonthLabel = new javax.swing.JLabel();
        LevelLabel = new javax.swing.JLabel();
        SubjectLabel = new javax.swing.JLabel();
        YearField = new javax.swing.JComboBox<>();
        MonthField = new javax.swing.JComboBox<>();
        LevelField = new javax.swing.JComboBox<>();
        SubjectField = new javax.swing.JComboBox<>();
        IncomeForLabel = new javax.swing.JLabel();
        IncomeReportScrollPane = new javax.swing.JScrollPane();
        IncomeReport = new javax.swing.JTable();
        TotalAmount = new javax.swing.JLabel();
        TotalAmountLabel = new javax.swing.JLabel();
        PaymentBackButton3 = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JSeparator();
        jPanel2 = new javax.swing.JPanel();
        StudentManagementTitle = new javax.swing.JLabel();

        PaymentPage.setMaximumSize(new java.awt.Dimension(930, 650));
        PaymentPage.setMinimumSize(new java.awt.Dimension(930, 650));
        PaymentPage.setPreferredSize(new java.awt.Dimension(930, 650));
        PaymentPage.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        PaymentTabbedPane.setMaximumSize(new java.awt.Dimension(850, 500));
        PaymentTabbedPane.setMinimumSize(new java.awt.Dimension(850, 500));
        PaymentTabbedPane.setPreferredSize(new java.awt.Dimension(850, 500));

        PaymentHistoryTab.setMaximumSize(new java.awt.Dimension(200, 200));
        PaymentHistoryTab.setMinimumSize(new java.awt.Dimension(200, 200));
        PaymentHistoryTab.setPreferredSize(new java.awt.Dimension(200, 200));
        PaymentHistoryTab.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        NoRecordsLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        NoRecordsLabel.setText("No payment records found.");
        PaymentHistoryTab.add(NoRecordsLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 96, 870, 300));

        GenerateReceiptButton.setText("Generate Receipt");
        GenerateReceiptButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                GenerateReceiptButtonActionPerformed(evt);
            }
        });
        PaymentHistoryTab.add(GenerateReceiptButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 430, 140, 35));

        AcceptPaymentButton.setText("Accept Payment");
        AcceptPaymentButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AcceptPaymentButtonActionPerformed(evt);
            }
        });
        PaymentHistoryTab.add(AcceptPaymentButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 430, 140, 35));

        PaymentBackButton.setText("Back");
        PaymentBackButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PaymentBackButtonActionPerformed(evt);
            }
        });
        PaymentHistoryTab.add(PaymentBackButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(830, 430, 70, 35));

        PaymentHistory.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        PaymentHistory.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "PMID", "Student ID", "Student Name", "Amount", "Date", "Payment Plan", "Payment Method"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        PaymentHistory.setRowHeight(30);
        PaymentHistory.setRowMargin(5);
        PaymentHistory.getTableHeader().setResizingAllowed(false);
        PaymentHistory.getTableHeader().setReorderingAllowed(false);
        PaymentHistory.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                PaymentHistoryMouseClicked(evt);
            }
        });
        PaymentHistory.addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentShown(java.awt.event.ComponentEvent evt) {
                PaymentHistoryComponentShown(evt);
            }
        });
        PaymentHistory.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                PaymentHistoryPropertyChange(evt);
            }
        });
        PaymentHistoryScrollPane.setViewportView(PaymentHistory);
        if (PaymentHistory.getColumnModel().getColumnCount() > 0) {
            PaymentHistory.getColumnModel().getColumn(0).setMinWidth(0);
            PaymentHistory.getColumnModel().getColumn(0).setPreferredWidth(0);
            PaymentHistory.getColumnModel().getColumn(0).setMaxWidth(0);
            PaymentHistory.getColumnModel().getColumn(1).setPreferredWidth(10);
            PaymentHistory.getColumnModel().getColumn(3).setPreferredWidth(10);
            PaymentHistory.getColumnModel().getColumn(4).setPreferredWidth(10);
            PaymentHistory.getColumnModel().getColumn(5).setPreferredWidth(10);
        }

        PaymentHistoryTab.add(PaymentHistoryScrollPane, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 75, 870, 320));

        HistoryYearField.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "All", "2021", "2022", "2023", "2024", "2025" }));
        HistoryYearField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                HistoryYearFieldActionPerformed(evt);
            }
        });
        PaymentHistoryTab.add(HistoryYearField, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 30, 70, 30));

        HistoryMonthField.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "All", "January", "February", "March", "April", "May", "June", "July", "August", "September", "October", "November", "December" }));
        HistoryMonthField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                HistoryMonthFieldActionPerformed(evt);
            }
        });
        PaymentHistoryTab.add(HistoryMonthField, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 30, 110, 30));

        PaymentTabbedPane.addTab("Payment History", PaymentHistoryTab);

        PendingPaymentsTab.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        NoRecordsLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        NoRecordsLabel1.setText("No payment records found.");
        PendingPaymentsTab.add(NoRecordsLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 96, 870, 300));

        PendingPayments.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        PendingPayments.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null}
            },
            new String [] {
                "Year", "Month", "Student ID", "Student Name", "Level", "Subject", "Amount"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        PendingPayments.setRowHeight(30);
        PendingPayments.setRowMargin(5);
        PendingPayments.getTableHeader().setResizingAllowed(false);
        PendingPayments.getTableHeader().setReorderingAllowed(false);
        PendingPayments.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                PendingPaymentsMouseClicked(evt);
            }
        });
        PendingPayments.addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentShown(java.awt.event.ComponentEvent evt) {
                PendingPaymentsComponentShown(evt);
            }
        });
        PendingPaymentsScrollPane.setViewportView(PendingPayments);
        if (PendingPayments.getColumnModel().getColumnCount() > 0) {
            PendingPayments.getColumnModel().getColumn(0).setPreferredWidth(10);
            PendingPayments.getColumnModel().getColumn(1).setPreferredWidth(10);
            PendingPayments.getColumnModel().getColumn(2).setPreferredWidth(10);
            PendingPayments.getColumnModel().getColumn(6).setPreferredWidth(10);
        }

        PendingPaymentsTab.add(PendingPaymentsScrollPane, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 75, 870, 320));

        OutstandingLabel.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        OutstandingLabel.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        OutstandingLabel.setText("Total Outstanding Amount:   RM");
        OutstandingLabel.setToolTipText("");
        OutstandingLabel.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);
        PendingPaymentsTab.add(OutstandingLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(35, 420, -1, -1));

        OutstandingAmount.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        OutstandingAmount.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        OutstandingAmount.setText("0");
        OutstandingAmount.setToolTipText("");
        OutstandingAmount.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);
        PendingPaymentsTab.add(OutstandingAmount, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 420, 180, -1));

        PaymentBackButton2.setText("Back");
        PaymentBackButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PaymentBackButton2ActionPerformed(evt);
            }
        });
        PendingPaymentsTab.add(PaymentBackButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(830, 430, 70, 35));

        PendingYearField.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "All", "2021", "2022", "2023", "2024", "2025" }));
        PendingYearField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PendingYearFieldActionPerformed(evt);
            }
        });
        PendingPaymentsTab.add(PendingYearField, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 30, 70, 30));

        PendingMonthField.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "All", "January", "February", "March", "April", "May", "June", "July", "August", "September", "October", "November", "December" }));
        PendingMonthField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PendingMonthFieldActionPerformed(evt);
            }
        });
        PendingPaymentsTab.add(PendingMonthField, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 30, 110, 30));

        PaymentTabbedPane.addTab("Pending Payments", PendingPaymentsTab);

        IncomeReportTab.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        YearLabel.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        YearLabel.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        YearLabel.setText("Year:");
        YearLabel.setToolTipText("");
        YearLabel.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);
        IncomeReportTab.add(YearLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 110, -1, 30));

        MonthLabel.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        MonthLabel.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        MonthLabel.setText("Month:");
        MonthLabel.setToolTipText("");
        MonthLabel.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);
        IncomeReportTab.add(MonthLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 150, -1, 30));

        LevelLabel.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        LevelLabel.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        LevelLabel.setText("Level:");
        LevelLabel.setToolTipText("");
        LevelLabel.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);
        IncomeReportTab.add(LevelLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 110, -1, 30));

        SubjectLabel.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        SubjectLabel.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        SubjectLabel.setText("Subject:");
        SubjectLabel.setToolTipText("");
        SubjectLabel.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);
        IncomeReportTab.add(SubjectLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 150, -1, 30));

        YearField.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "All", "2021", "2022", "2023", "2024", "2025" }));
        YearField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                YearFieldActionPerformed(evt);
            }
        });
        IncomeReportTab.add(YearField, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 110, 110, 30));

        MonthField.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "All", "January", "February", "March", "April", "May", "June", "July", "August", "September", "October", "November", "December" }));
        MonthField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MonthFieldActionPerformed(evt);
            }
        });
        IncomeReportTab.add(MonthField, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 150, 110, 30));

        LevelField.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "All", "Form 1", "Form 2", "Form 3", "Form 4", "Form 5" }));
        LevelField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LevelFieldActionPerformed(evt);
            }
        });
        IncomeReportTab.add(LevelField, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 110, 110, 30));

        SubjectField.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "All", "English", "Mathematics", "Science" }));
        SubjectField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SubjectFieldActionPerformed(evt);
            }
        });
        IncomeReportTab.add(SubjectField, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 150, 110, 30));

        IncomeForLabel.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        IncomeForLabel.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        IncomeForLabel.setText("ATC Tuition Center Income Report");
        IncomeForLabel.setToolTipText("");
        IncomeForLabel.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);
        IncomeReportTab.add(IncomeForLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 50, 440, 30));

        IncomeReport.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {"Cash", null},
                {"Credit Card", null},
                {"Bank Transfer", null},
                {"E-Wallet", null}
            },
            new String [] {
                "Payment Method", "Amount"
            }
        ));
        IncomeReport.setRowHeight(30);
        IncomeReport.setRowMargin(5);
        IncomeReportScrollPane.setViewportView(IncomeReport);

        IncomeReportTab.add(IncomeReportScrollPane, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 210, 440, 150));

        TotalAmount.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        TotalAmount.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        TotalAmount.setText("0");
        TotalAmount.setToolTipText("");
        TotalAmount.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);
        IncomeReportTab.add(TotalAmount, new org.netbeans.lib.awtextra.AbsoluteConstraints(405, 380, 280, 30));

        TotalAmountLabel.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        TotalAmountLabel.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        TotalAmountLabel.setText("Total Income:   RM");
        TotalAmountLabel.setToolTipText("");
        TotalAmountLabel.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);
        IncomeReportTab.add(TotalAmountLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 380, -1, 30));

        PaymentBackButton3.setText("Back");
        PaymentBackButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PaymentBackButton3ActionPerformed(evt);
            }
        });
        IncomeReportTab.add(PaymentBackButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(830, 430, 70, 35));
        IncomeReportTab.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 90, 440, 10));

        PaymentTabbedPane.addTab("Income Report", IncomeReportTab);

        PaymentPage.add(PaymentTabbedPane, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 100, 930, 550));

        jPanel2.setBackground(new java.awt.Color(184, 186, 191));
        jPanel2.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        StudentManagementTitle.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        StudentManagementTitle.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        StudentManagementTitle.setText("Payment");
        StudentManagementTitle.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(StudentManagementTitle, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 926, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addComponent(StudentManagementTitle)
                .addContainerGap(33, Short.MAX_VALUE))
        );

        PaymentPage.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 930, 100));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 930, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(PaymentPage, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 650, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(PaymentPage, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void GenerateReceiptButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_GenerateReceiptButtonActionPerformed
        int row = PaymentHistory.getSelectedRow();
        String pmid = (String) PaymentHistory.getValueAt(row, 0);
        try {
            ReceiptMethod.GenerateReceipt(AdminMethods.AdminSession.getAdminid(), PaymentMethods.GetPaymentMadeByID(pmid));
            JOptionPane.showMessageDialog(this, "Receipt successfully generated.\nPlease find the generated receipt in the Receipts folder.", "Successful Receipt Generation", JOptionPane.PLAIN_MESSAGE);
        } catch (IOException ex) {
            ex.printStackTrace();
        }
    }//GEN-LAST:event_GenerateReceiptButtonActionPerformed

    private void PaymentBackButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PaymentBackButtonActionPerformed
        parent.switchPanel("admin");
    }//GEN-LAST:event_PaymentBackButtonActionPerformed

    private void AcceptPaymentButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AcceptPaymentButtonActionPerformed
        PopupAcceptPayment popup = new PopupAcceptPayment();
        JButton[] options = {popup.getAPOKButton(), popup.getAPCancelButton()};
        JButton okbutton = options[0];
        JOptionPane.showOptionDialog(this, popup, "Accept New Payment", JOptionPane.DEFAULT_OPTION, JOptionPane.PLAIN_MESSAGE, null, options, okbutton);
        
        if (popup.getAPChoice() == 0) {
            int choice = JOptionPane.showConfirmDialog(this, "Confirm accepting new payment?", "New Payment Acceptance Confirmation", JOptionPane.YES_NO_OPTION);
            
            if (choice == JOptionPane.YES_OPTION) {
                String newpmid = PaymentMethods.GetNewPaymentMadeID();
                
                String studentid = popup.getStudentIDField().getSelectedItem().toString();
                
                String newpmplan = popup.getPaymentPlanField().getSelectedItem().toString();
                
                String paymentyear = null;
                String paymentmonth = null;
                
                List<Payment> payments = PaymentMethods.GetAllPayments();
                
                List<String> paymentids = new ArrayList<>();
                float newpmamt = 0;
                
                if (newpmplan.equals("Monthly")) {
                    paymentmonth = popup.getPaymentForMonthField().getSelectedItem().toString();
                    paymentyear = popup.getPaymentForYearField().getSelectedItem().toString();
                    
                    for (Payment p : payments) {
                        if (p.getPaymentstatus().equals("Pending") && p.getStudentid().equals(studentid) && p.getPaymentyear().equals(paymentyear) && p.getPaymentmonth().equals(paymentmonth)) {
                        paymentids.add(p.getPaymentid());
                        newpmamt += p.getPaymentamount();
                        p.setPaymentstatus("Paid");
                        }
                    }
                } else if (newpmplan.equals("Yearly")) {
                    paymentyear = popup.getPaymentForYearField().getSelectedItem().toString();
                    
                    for (Payment p : payments) {
                        if (p.getPaymentstatus().equals("Pending") && p.getStudentid().equals(studentid) && p.getPaymentyear().equals(paymentyear)) {
                        paymentids.add(p.getPaymentid());
                        newpmamt += p.getPaymentamount();
                        }
                    }
                }
                
                String newpmfor;
                
                if (paymentids.size() > 1) {
                    newpmfor = String.join(";", paymentids);
                } else {
                    newpmfor = paymentids.get(0);
                }
                
                String newpmdate = GeneralMethods.GetCurrentDate();
                String newpmmethod = popup.getPaymentMethodField().getSelectedItem().toString();
                
                
                PaymentMade newpayment = new PaymentMade(newpmid, studentid, newpmfor, newpmamt, newpmdate, newpmplan, newpmmethod);
                PaymentMethods.SaveNewPayment(newpayment);
                
                for (String paymentid : paymentids) {
                    Payment updatedpayment = PaymentMethods.GetPaymentByID(paymentid);
                    PaymentMethods.UpdatePaymentStatus(updatedpayment);
                }
                
                PaymentMethods.PopulateStudentPending(popup.getAPStudentid(), (DefaultTableModel) popup.getStudentPendingPayments().getModel());
                
                this.paymenthistorymodel = (DefaultTableModel) PaymentHistory.getModel();
                PaymentMethods.PopulatePaymentHistory(paymenthistorymodel, HistoryYearField.getSelectedItem().toString(), HistoryMonthField.getSelectedItem().toString());
                
                this.pendingpaymentsmodel = (DefaultTableModel) PendingPayments.getModel();
                PaymentMethods.PopulatePendingPayments(pendingpaymentsmodel, PendingYearField.getSelectedItem().toString(), PendingMonthField.getSelectedItem().toString());

                this.incomereportmodel = (DefaultTableModel) IncomeReport.getModel();
                PaymentMethods.PopulateIncomeReport(incomereportmodel, TotalAmount, YearField.getSelectedItem().toString(), MonthField.getSelectedItem().toString(), LevelField.getSelectedItem().toString(), SubjectField.getSelectedItem().toString());
                
            } else {
                return;
            }
        }

    }//GEN-LAST:event_AcceptPaymentButtonActionPerformed

    private void PaymentHistoryMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_PaymentHistoryMouseClicked

    }//GEN-LAST:event_PaymentHistoryMouseClicked

    private void PaymentHistoryComponentShown(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_PaymentHistoryComponentShown

    }//GEN-LAST:event_PaymentHistoryComponentShown

    private void PendingPaymentsMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_PendingPaymentsMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_PendingPaymentsMouseClicked

    private void PendingPaymentsComponentShown(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_PendingPaymentsComponentShown
        // TODO add your handling code here:
    }//GEN-LAST:event_PendingPaymentsComponentShown

    private void PaymentBackButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PaymentBackButton2ActionPerformed
        parent.switchPanel("admin");
    }//GEN-LAST:event_PaymentBackButton2ActionPerformed

    private void PaymentBackButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PaymentBackButton3ActionPerformed
        parent.switchPanel("admin");
    }//GEN-LAST:event_PaymentBackButton3ActionPerformed

    private void LevelFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LevelFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_LevelFieldActionPerformed

    private void SubjectFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SubjectFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_SubjectFieldActionPerformed

    private void PendingMonthFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PendingMonthFieldActionPerformed
        PaymentMethods.PopulatePendingPayments(pendingpaymentsmodel, PendingYearField.getSelectedItem().toString(), PendingMonthField.getSelectedItem().toString());
        if (PendingPayments.getRowCount() == 0) {
            NoRecordsLabel1.setVisible(true);
        } else {
            NoRecordsLabel1.setVisible(false);
        }
    }//GEN-LAST:event_PendingMonthFieldActionPerformed

    private void HistoryMonthFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_HistoryMonthFieldActionPerformed
        PaymentMethods.PopulatePaymentHistory(paymenthistorymodel, HistoryYearField.getSelectedItem().toString(), HistoryMonthField.getSelectedItem().toString());
        if (PaymentHistory.getRowCount() == 0) {
            NoRecordsLabel.setVisible(true);
        } else {
            NoRecordsLabel.setVisible(false);
        }
    }//GEN-LAST:event_HistoryMonthFieldActionPerformed

    private void PendingYearFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PendingYearFieldActionPerformed
        PaymentMethods.PopulatePendingPayments(pendingpaymentsmodel, PendingYearField.getSelectedItem().toString(), PendingMonthField.getSelectedItem().toString());
        if (PendingPayments.getRowCount() == 0) {
            NoRecordsLabel1.setVisible(true);
        } else {
            NoRecordsLabel1.setVisible(false);
        }
    }//GEN-LAST:event_PendingYearFieldActionPerformed

    private void HistoryYearFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_HistoryYearFieldActionPerformed
        PaymentMethods.PopulatePaymentHistory(paymenthistorymodel, HistoryYearField.getSelectedItem().toString(), HistoryMonthField.getSelectedItem().toString());
        if (PaymentHistory.getRowCount() == 0) {
            NoRecordsLabel.setVisible(true);
        } else {
            NoRecordsLabel.setVisible(false);
        }
    }//GEN-LAST:event_HistoryYearFieldActionPerformed

    private void PaymentHistoryPropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_PaymentHistoryPropertyChange

    }//GEN-LAST:event_PaymentHistoryPropertyChange

    private void MonthFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MonthFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_MonthFieldActionPerformed

    private void YearFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_YearFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_YearFieldActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton AcceptPaymentButton;
    private javax.swing.JButton GenerateReceiptButton;
    private javax.swing.JComboBox<String> HistoryMonthField;
    private javax.swing.JComboBox<String> HistoryYearField;
    private javax.swing.JLabel IncomeForLabel;
    private javax.swing.JTable IncomeReport;
    private javax.swing.JScrollPane IncomeReportScrollPane;
    private javax.swing.JPanel IncomeReportTab;
    private javax.swing.JComboBox<String> LevelField;
    private javax.swing.JLabel LevelLabel;
    private javax.swing.JComboBox<String> MonthField;
    private javax.swing.JLabel MonthLabel;
    private javax.swing.JLabel NoRecordsLabel;
    private javax.swing.JLabel NoRecordsLabel1;
    private javax.swing.JLabel OutstandingAmount;
    private javax.swing.JLabel OutstandingLabel;
    private javax.swing.JButton PaymentBackButton;
    private javax.swing.JButton PaymentBackButton2;
    private javax.swing.JButton PaymentBackButton3;
    private javax.swing.JTable PaymentHistory;
    private javax.swing.JScrollPane PaymentHistoryScrollPane;
    private javax.swing.JPanel PaymentHistoryTab;
    private javax.swing.JPanel PaymentPage;
    private javax.swing.JTabbedPane PaymentTabbedPane;
    private javax.swing.JComboBox<String> PendingMonthField;
    private javax.swing.JTable PendingPayments;
    private javax.swing.JScrollPane PendingPaymentsScrollPane;
    private javax.swing.JPanel PendingPaymentsTab;
    private javax.swing.JComboBox<String> PendingYearField;
    private javax.swing.JLabel StudentManagementTitle;
    private javax.swing.JComboBox<String> SubjectField;
    private javax.swing.JLabel SubjectLabel;
    private javax.swing.JLabel TotalAmount;
    private javax.swing.JLabel TotalAmountLabel;
    private javax.swing.JComboBox<String> YearField;
    private javax.swing.JLabel YearLabel;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JSeparator jSeparator1;
    // End of variables declaration//GEN-END:variables
}
