/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package AdminFrontend;

import AdminBackend.GeneralMethods;
import java.awt.Window;
import java.util.List;
import javax.swing.JButton;
import javax.swing.JLabel;
import javax.swing.JTextField;
import javax.swing.SwingUtilities;

/**
 *
 * @author User
 */
public class PopupLoginCredentials extends javax.swing.JPanel {
    private final int[] choice = {-1};
    JButton okbutton = new JButton("OK");
    JButton cancelbutton = new JButton("Cancel");
    String oldusername;
    String oldpassword;
    /**
     * Creates new form LoginCredentialsPopup
     */
    public PopupLoginCredentials(List<String> logincreds) {
        initComponents();
        oldusername = logincreds.get(0);
        oldpassword = logincreds.get(1);
        UsernameField.setText(oldusername);
        PasswordField.setText(oldpassword);
        okbutton.setEnabled(false);
        
        okbutton.addActionListener(e -> {
            choice[0] = 0;
            Window w = SwingUtilities.getWindowAncestor(okbutton);
            if (w != null) w.dispose();
        });

        this.cancelbutton.addActionListener(e -> {
            choice[0] = 1;
            Window w = SwingUtilities.getWindowAncestor(cancelbutton);
            if (w != null) w.dispose();
        });
    }
    
    public String getNewUsername() {
        return UsernameField.getText().trim();
    }
    
    public String getNewPassword() {
        return PasswordField.getText().trim();
    }

    public void setPassword(String password) {
        this.PasswordField.setText(password);
        PasswordField.revalidate();
        PasswordField.repaint();
    }

    public void setUsername(String username) {
        this.UsernameField.setText(username);
        UsernameField.revalidate();
        UsernameField.repaint();
    }

    public JTextField getPasswordField() {
        return PasswordField;
    }

    public JLabel getPasswordLabel() {
        return PasswordLabel;
    }

    public JTextField getUsernameField() {
        return UsernameField;
    }

    public JLabel getUsernameLabel() {
        return UsernameLabel;
    }
    
    public JButton getLCOKButton() {
        return okbutton;
    }
    
    public JButton getLCCancelButton() {
        return cancelbutton;
    }
    
    public int getLCChoice() {
        return choice[0];
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        UsernameField = new javax.swing.JTextField();
        PasswordField = new javax.swing.JTextField();
        UsernameLabel = new javax.swing.JLabel();
        PasswordLabel = new javax.swing.JLabel();
        EditUsernameToggle = new javax.swing.JToggleButton();
        EditPasswordToggle = new javax.swing.JToggleButton();

        setPreferredSize(new java.awt.Dimension(400, 180));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        UsernameField.setEditable(false);
        UsernameField.setBackground(new java.awt.Color(214, 217, 223));
        UsernameField.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        UsernameField.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                UsernameFieldFocusLost(evt);
            }
        });
        add(UsernameField, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 50, 210, 30));

        PasswordField.setEditable(false);
        PasswordField.setBackground(new java.awt.Color(214, 217, 223));
        PasswordField.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        PasswordField.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                PasswordFieldFocusLost(evt);
            }
        });
        add(PasswordField, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 100, 210, 30));

        UsernameLabel.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        UsernameLabel.setText("Username");
        add(UsernameLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 50, -1, 30));

        PasswordLabel.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        PasswordLabel.setText("Password");
        add(PasswordLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 100, -1, 30));

        EditUsernameToggle.setText("EDIT");
        EditUsernameToggle.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EditUsernameToggleActionPerformed(evt);
            }
        });
        add(EditUsernameToggle, new org.netbeans.lib.awtextra.AbsoluteConstraints(322, 50, 60, 30));

        EditPasswordToggle.setText("EDIT");
        EditPasswordToggle.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EditPasswordToggleActionPerformed(evt);
            }
        });
        add(EditPasswordToggle, new org.netbeans.lib.awtextra.AbsoluteConstraints(322, 100, 60, 30));
    }// </editor-fold>//GEN-END:initComponents

    private void EditUsernameToggleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EditUsernameToggleActionPerformed
        UsernameField.setEditable(true);
        if (EditUsernameToggle.isSelected()) {
            EditUsernameToggle.setText("SAVE");
            UsernameField.setBackground(new java.awt.Color(255, 255, 255));
            okbutton.setEnabled(false);
            EditPasswordToggle.setEnabled(false);
        } else {
            EditUsernameToggle.setText("EDIT");
            UsernameField.setBackground(new java.awt.Color(214, 217, 223));
            EditPasswordToggle.setEnabled(true);
            
            boolean changed = !UsernameField.getText().trim().equals(oldusername) || !PasswordField.getText().trim().equals(oldpassword);
            okbutton.setEnabled(changed);
        }
    }//GEN-LAST:event_EditUsernameToggleActionPerformed

    private void EditPasswordToggleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EditPasswordToggleActionPerformed
        PasswordField.setEditable(true);
        if (EditPasswordToggle.isSelected()) {
            EditPasswordToggle.setText("SAVE");
            PasswordField.setBackground(new java.awt.Color(255, 255, 255));
            okbutton.setEnabled(false);
            EditUsernameToggle.setEnabled(false);
        } else {
            EditPasswordToggle.setText("EDIT");
            PasswordField.setBackground(new java.awt.Color(214, 217, 223));
            EditUsernameToggle.setEnabled(true);
            
            boolean changed = !UsernameField.getText().trim().equals(oldusername) || !PasswordField.getText().trim().equals(oldpassword);
            okbutton.setEnabled(changed);
        }
    }//GEN-LAST:event_EditPasswordToggleActionPerformed

    private void UsernameFieldFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_UsernameFieldFocusLost
        GeneralMethods.InputValidation(UsernameField, oldusername, 5, 20, "[a-zA-Z0-9]+", "Invalid username entered.\nPlease make sure uinput does not contain any illegal characters and is within 5-20 characters.");
        okbutton.setEnabled(false);
    }//GEN-LAST:event_UsernameFieldFocusLost

    private void PasswordFieldFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_PasswordFieldFocusLost
        GeneralMethods.InputValidation(PasswordField, oldpassword, 8, Integer.MAX_VALUE, "^.+$", "Please enter a password that is at least 8 characters long.");
        okbutton.setEnabled(false);
    }//GEN-LAST:event_PasswordFieldFocusLost


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JToggleButton EditPasswordToggle;
    private javax.swing.JToggleButton EditUsernameToggle;
    private javax.swing.JTextField PasswordField;
    private javax.swing.JLabel PasswordLabel;
    private javax.swing.JTextField UsernameField;
    private javax.swing.JLabel UsernameLabel;
    // End of variables declaration//GEN-END:variables
}
