/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package AdminFrontend;

import AdminBackend.AdminMethods;
import AdminBackend.GeneralMethods;
import java.awt.Window;
import javax.swing.JButton;
import javax.swing.SwingUtilities;

/**
 *
 * @author User
 */
public class PopupContactInfo extends javax.swing.JPanel {
    private final int[] choice = {-1};
    JButton okbutton = new JButton("OK");
    JButton cancelbutton = new JButton("Cancel");
    String oldph;
    String oldemail;
    
    /**
     * Creates new form LoginCredentialsPopup
     */
    public PopupContactInfo(String ph, String email) {
        initComponents();
        oldph = ph;
        oldemail = email;
        PHField.setText(oldph.substring(3));
        EmailField.setText(oldemail);
        okbutton.setEnabled(false);
        
        String currentadminid = AdminMethods.AdminSession.getAdminid();
        
        okbutton.addActionListener(e -> {
            choice[0] = 0;
            Window w = SwingUtilities.getWindowAncestor(okbutton);
            if (w != null) w.dispose();
        });

        this.cancelbutton.addActionListener(e -> {
            choice[0] = 1;
            Window w = SwingUtilities.getWindowAncestor(cancelbutton);
            if (w != null) w.dispose();
        });
    }
    
    public String getNewPH() {
        return PHField.getText().trim();
    }
    
    public String getNewEmail() {
        return EmailField.getText().trim();
    }

    public void setEmail(String email) {
        this.EmailField.setText(email);
        EmailField.revalidate();
        EmailField.repaint();
    }

    public void setPH(String ph) {
        this.PHField.setText(ph);
        PHField.revalidate();
        PHField.repaint();
    }

    public JButton getCIOKButton() {
        return okbutton;
    }
    
    public JButton getCICancelButton() {
        return cancelbutton;
    }
    
    public int getCIChoice() {
        return choice[0];
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        PHField = new javax.swing.JTextField();
        EmailField = new javax.swing.JTextField();
        PHLabel = new javax.swing.JLabel();
        EmailLabel = new javax.swing.JLabel();
        EditPHToggle = new javax.swing.JToggleButton();
        EditEmailToggle = new javax.swing.JToggleButton();
        plus60Label = new javax.swing.JLabel();

        setPreferredSize(new java.awt.Dimension(400, 180));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        PHField.setEditable(false);
        PHField.setBackground(new java.awt.Color(214, 217, 223));
        PHField.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        PHField.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                PHFieldFocusLost(evt);
            }
        });
        add(PHField, new org.netbeans.lib.awtextra.AbsoluteConstraints(165, 50, 145, 30));

        EmailField.setEditable(false);
        EmailField.setBackground(new java.awt.Color(214, 217, 223));
        EmailField.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        EmailField.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                EmailFieldFocusLost(evt);
            }
        });
        add(EmailField, new org.netbeans.lib.awtextra.AbsoluteConstraints(135, 100, 175, 30));

        PHLabel.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        PHLabel.setText("Phone Number");
        add(PHLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 50, -1, 30));

        EmailLabel.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        EmailLabel.setText("Email Address");
        add(EmailLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 100, -1, 30));

        EditPHToggle.setText("EDIT");
        EditPHToggle.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EditPHToggleActionPerformed(evt);
            }
        });
        add(EditPHToggle, new org.netbeans.lib.awtextra.AbsoluteConstraints(322, 50, 60, 30));

        EditEmailToggle.setText("EDIT");
        EditEmailToggle.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EditEmailToggleActionPerformed(evt);
            }
        });
        add(EditEmailToggle, new org.netbeans.lib.awtextra.AbsoluteConstraints(322, 100, 60, 30));

        plus60Label.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        plus60Label.setText("+60");
        add(plus60Label, new org.netbeans.lib.awtextra.AbsoluteConstraints(135, 50, 30, 30));
    }// </editor-fold>//GEN-END:initComponents

    private void EditPHToggleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EditPHToggleActionPerformed
        if (EditPHToggle.isSelected()) {
            EditPHToggle.setText("SAVE");
            PHField.setEditable(true);
            PHField.setBackground(new java.awt.Color(255, 255, 255));
            okbutton.setEnabled(false);
        } else {
            EditPHToggle.setText("EDIT");
            PHField.setEditable(false);
            PHField.setBackground(new java.awt.Color(214, 217, 223));
            
            boolean changed = !PHField.getText().trim().equals(oldph.substring(3)) || !EmailField.getText().trim().equals(oldemail);
            okbutton.setEnabled(changed);
        }
    }//GEN-LAST:event_EditPHToggleActionPerformed

    private void EditEmailToggleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EditEmailToggleActionPerformed
        if (EditEmailToggle.isSelected()) {
            EditEmailToggle.setText("SAVE");
            EmailField.setEditable(true);
            EmailField.setBackground(new java.awt.Color(255, 255, 255));
            okbutton.setEnabled(false);
        } else {
            EditEmailToggle.setText("EDIT");
            EmailField.setEditable(false);
            EmailField.setBackground(new java.awt.Color(214, 217, 223));
            
            boolean changed = !PHField.getText().trim().equals(oldph.substring(3)) || !EmailField.getText().trim().equals(oldemail);
            okbutton.setEnabled(changed);
        }
    }//GEN-LAST:event_EditEmailToggleActionPerformed

    private void PHFieldFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_PHFieldFocusLost
        GeneralMethods.InputValidation(PHField, oldph.substring(3), 9, 9, "\\d+", "Invalid phone number entered.\nPlease make sure input only contains digits and is exactly 9 characters long excluding the country code (+60).");
        okbutton.setEnabled(false);
    }//GEN-LAST:event_PHFieldFocusLost

    private void EmailFieldFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_EmailFieldFocusLost
        GeneralMethods.InputValidation(EmailField, oldemail, 0, Integer.MAX_VALUE, "^[\\w.-]+@[\\w.-]+\\.\\w+$", "Invalid email address entered.\nPlease make sure input does not contain any illegal characters and includes the email domain (Example: @gmail.com).");
        okbutton.setEnabled(false);
    }//GEN-LAST:event_EmailFieldFocusLost


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JToggleButton EditEmailToggle;
    private javax.swing.JToggleButton EditPHToggle;
    private javax.swing.JTextField EmailField;
    private javax.swing.JLabel EmailLabel;
    private javax.swing.JTextField PHField;
    private javax.swing.JLabel PHLabel;
    private javax.swing.JLabel plus60Label;
    // End of variables declaration//GEN-END:variables
}
