package ATCLogin;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

import AdminBackend.AdminMethods.AdminSession;
import AdminFrontend.AdminFrame;
import StudentFrontend.StudentPage;
import StudentFrontend.StudentPage.StudentSession;
import TutorFrontend.atctdgui;
import java.io.File;
import java.io.FileReader;
import java.io.BufferedReader;
import java.io.IOException;
import javax.swing.JOptionPane;
import javax.swing.Timer;
/**
 *
 * @author snpha
 */
public class Login extends javax.swing.JFrame {
    private static final int locktime = 60; 
    private int maxtries = 3;
    private int remainingtries = maxtries;
    private int secondsremaining;
    private Timer countdowntimer;
    private Timer unlocktimer;
    
    /**
     * Creates new form LoginFrame
     */
    public Login() {
        initComponents();
        RemainingTriesLabel.setVisible(false);
        SystemLockLabel.setVisible(false);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        LoginPage = new javax.swing.JPanel();
        ATCLabel = new javax.swing.JLabel();
        MSLabel = new javax.swing.JLabel();
        LoginButton = new javax.swing.JButton();
        RemainingTriesLabel = new javax.swing.JLabel();
        SystemLockLabel = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        UsernameLabel = new javax.swing.JLabel();
        PasswordField = new javax.swing.JPasswordField();
        PasswordLabel = new javax.swing.JLabel();
        UsernameField = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(930, 650));
        getContentPane().setLayout(new java.awt.GridBagLayout());

        LoginPage.setMaximumSize(new java.awt.Dimension(930, 650));
        LoginPage.setMinimumSize(new java.awt.Dimension(930, 650));
        LoginPage.setPreferredSize(new java.awt.Dimension(930, 650));
        LoginPage.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        ATCLabel.setFont(new java.awt.Font("Segoe UI", 1, 30)); // NOI18N
        ATCLabel.setText("Advanced Tuition Center (ATC)");
        LoginPage.add(ATCLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 110, 440, -1));

        MSLabel.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        MSLabel.setText("Management System");
        LoginPage.add(MSLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 160, -1, -1));

        LoginButton.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        LoginButton.setText("LOGIN");
        LoginButton.setPreferredSize(new java.awt.Dimension(130, 40));
        LoginButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LoginButtonActionPerformed(evt);
            }
        });
        LoginPage.add(LoginButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 490, 150, 50));

        RemainingTriesLabel.setText(" Remaining Login Attempts (2/3)");
        RemainingTriesLabel.setPreferredSize(new java.awt.Dimension(335, 16));
        LoginPage.add(RemainingTriesLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(245, 425, 440, -1));

        SystemLockLabel.setText(" System locked for ___ seconds.");
        SystemLockLabel.setPreferredSize(new java.awt.Dimension(335, 16));
        LoginPage.add(SystemLockLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(245, 445, 440, -1));

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        UsernameLabel.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        UsernameLabel.setText("Username");
        UsernameLabel.setToolTipText("");

        PasswordField.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        PasswordField.setPreferredSize(new java.awt.Dimension(200, 28));

        PasswordLabel.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        PasswordLabel.setText("Password");

        UsernameField.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        UsernameField.setMaximumSize(new java.awt.Dimension(200, 25));
        UsernameField.setMinimumSize(new java.awt.Dimension(200, 25));
        UsernameField.setName(""); // NOI18N
        UsernameField.setPreferredSize(new java.awt.Dimension(200, 25));
        UsernameField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                UsernameFieldActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(PasswordLabel)
                    .addComponent(UsernameLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 45, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(UsernameField, javax.swing.GroupLayout.DEFAULT_SIZE, 250, Short.MAX_VALUE)
                    .addComponent(PasswordField, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(35, 35, 35))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(UsernameField, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(UsernameLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(26, 26, 26)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(PasswordField, javax.swing.GroupLayout.DEFAULT_SIZE, 30, Short.MAX_VALUE)
                    .addComponent(PasswordLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(40, Short.MAX_VALUE))
        );

        LoginPage.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(245, 240, 440, 170));

        getContentPane().add(LoginPage, new java.awt.GridBagConstraints());

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void LoginButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LoginButtonActionPerformed
        boolean found = false;
        
        try {
            File passwordfile = new File("Text Files/users.txt");
            FileReader fr = new FileReader(passwordfile);
            BufferedReader br = new BufferedReader(fr);

            String line;

            while ((line = br.readLine()) != null) {
                String[] parts = line.split(",");
                String id = parts[0];
                String username = parts[1];
                String password = parts[2];

                if (username.equalsIgnoreCase(UsernameField.getText())) {
                    found = true;
                    String userid = parts[0];
                    char role = userid.charAt(0);
                    
                    switch(role) {

                        // Admin login
                        case 'A':
                            RemainingTriesLabel.setVisible(false);
                            SystemLockLabel.setVisible(false);
                            if (password.equals(new String(PasswordField.getPassword()))) {
                                JOptionPane.showMessageDialog(null, "Login successful!");
                                AdminSession.setAdminid(parts[0]);

                                try {
                                    new AdminFrame().setVisible(true);
                                } catch (Exception ex) {
                                    ex.printStackTrace();
                                }
                                this.dispose();
                                
                            } else {
                                JOptionPane.showMessageDialog(null, "Password is incorrect. Please try again.");
                            }
                            
                            return;

                        // Student login
                        case 'S':
                            if (password.equals(new String(PasswordField.getPassword()))) {
                                JOptionPane.showMessageDialog(null, "Login successful!");
                                remainingtries = maxtries;
                                StudentSession.setStudentid(parts[0]);

                                try {
                                    new StudentPage().setVisible(true);
                                } catch (Exception ex) {
                                    ex.printStackTrace();
                                }
                                this.dispose();
                                
                            } else {
                                HandleLoginAttempt();
                                RemainingTriesLabel.setText("Remaining Login Attempts (" + remainingtries + "/" + maxtries + ")");
                                RemainingTriesLabel.setVisible(true);
                            }
                            
                            return;

                        // Tutor login
                        case 'T':                    
                            if (password.equals(new String(PasswordField.getPassword()))) {
                                JOptionPane.showMessageDialog(null, "Login successful!");
                                remainingtries = maxtries; 

                                try {
                                    new atctdgui(userid).setVisible(true);
                                } catch (Exception ex) {
                                    ex.printStackTrace();
                                }
                                this.dispose();
                                
                            } else {
                                HandleLoginAttempt();
                                RemainingTriesLabel.setText("Remaining Login Attempts (" + remainingtries + "/" + maxtries + ")");
                                RemainingTriesLabel.setVisible(true);
                            }
                            
                            return;

                        default:
                            JOptionPane.showMessageDialog(null, "Unknown role: " + role);
                            return;
                    }
                }
            }
            
            if (!found) {
                JOptionPane.showMessageDialog(this, "User not found. Please try again.");
            }
            
        } catch (IOException ex) {
            ex.printStackTrace();
        }
    }//GEN-LAST:event_LoginButtonActionPerformed

    private void UsernameFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_UsernameFieldActionPerformed
        // TODdO add your handling code here:
    }//GEN-LAST:event_UsernameFieldActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Login().setVisible(true);
            }
        });
    }
    
    private void HandleLoginAttempt() {
        remainingtries--;
        if (remainingtries > 0) {
            JOptionPane.showMessageDialog(this, "Password is incorrect. Please try again.");
            RemainingTriesLabel.setText("Remaining Login Attempts (" + remainingtries + "/" + maxtries + ")");
            return;
        }
        
        // Disable UI if max login attempts have been reached
        UsernameField.setEnabled(false);
        PasswordField.setEnabled(false);
        LoginButton.setEnabled(false);
        
        // Countdown timer for system lock
        secondsremaining = locktime;
        SystemLockLabel.setVisible(true);
        RemainingTriesLabel.setText("Maximum number of login attempts reached. ");
        SystemLockLabel.setText("System locked for " + secondsremaining +" seconds.");
        

        // Every 1 second, tick down and update the label
        countdowntimer = new Timer(1000, e -> {
            secondsremaining--;
            RemainingTriesLabel.setText("Maximum number of login attempts reached. ");
            SystemLockLabel.setText("System locked for " + secondsremaining +" seconds.");
            if (secondsremaining <= 0) {
                countdowntimer.stop();
            }
         });
        countdowntimer.start();
        
        // Timer for system lock
        unlocktimer = new Timer(locktime * 1000, e -> {
            UsernameField.setEnabled(true);
            PasswordField.setEnabled(true);
            LoginButton.setEnabled(true);
            SystemLockLabel.setVisible(false);
            RemainingTriesLabel.setVisible(false);
            remainingtries = maxtries;
        });
        unlocktimer.setRepeats(false);
        unlocktimer.start();
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel ATCLabel;
    private javax.swing.JButton LoginButton;
    private javax.swing.JPanel LoginPage;
    private javax.swing.JLabel MSLabel;
    private javax.swing.JPasswordField PasswordField;
    private javax.swing.JLabel PasswordLabel;
    private javax.swing.JLabel RemainingTriesLabel;
    private javax.swing.JLabel SystemLockLabel;
    private javax.swing.JTextField UsernameField;
    private javax.swing.JLabel UsernameLabel;
    private javax.swing.JPanel jPanel2;
    // End of variables declaration//GEN-END:variables
}
